export const words = [
  // HSK 1
  { hanzi: "爱", pinyin: "ài", meaning: "love", level: "HSK1" },
  { hanzi: "八", pinyin: "bā", meaning: "eight", level: "HSK1" },
  { hanzi: "爸爸", pinyin: "bà ba", meaning: "father", level: "HSK1" },
  { hanzi: "杯子", pinyin: "bēi zi", meaning: "cup", level: "HSK1" },
  { hanzi: "北京", pinyin: "běi jīng", meaning: "Beijing", level: "HSK1" },
  { hanzi: "本", pinyin: "běn", meaning: "measure word (books)", level: "HSK1" },
  { hanzi: "不", pinyin: "bù", meaning: "not", level: "HSK1" },
  { hanzi: "不客气", pinyin: "bù kè qi", meaning: "you're welcome", level: "HSK1" },
  { hanzi: "菜", pinyin: "cài", meaning: "dish / food", level: "HSK1" },
  { hanzi: "茶", pinyin: "chá", meaning: "tea", level: "HSK1" },
  { hanzi: "吃", pinyin: "chī", meaning: "eat", level: "HSK1" },
  { hanzi: "出租车", pinyin: "chū zū chē", meaning: "taxi", level: "HSK1" },
  { hanzi: "打电话", pinyin: "dǎ diàn huà", meaning: "make a call", level: "HSK1" },
  { hanzi: "大", pinyin: "dà", meaning: "big", level: "HSK1" },
  { hanzi: "的", pinyin: "de", meaning: "possessive particle", level: "HSK1" },
  { hanzi: "点", pinyin: "diǎn", meaning: "o'clock / dot", level: "HSK1" },
  { hanzi: "电脑", pinyin: "diàn nǎo", meaning: "computer", level: "HSK1" },
  { hanzi: "电视", pinyin: "diàn shì", meaning: "TV", level: "HSK1" },
  { hanzi: "电影", pinyin: "diàn yǐng", meaning: "movie", level: "HSK1" },
  { hanzi: "东西", pinyin: "dōng xi", meaning: "thing", level: "HSK1" },
  { hanzi: "都", pinyin: "dōu", meaning: "all", level: "HSK1" },
  { hanzi: "读", pinyin: "dú", meaning: "read", level: "HSK1" },
  { hanzi: "对不起", pinyin: "duì bu qǐ", meaning: "sorry", level: "HSK1" },
  { hanzi: "多", pinyin: "duō", meaning: "many", level: "HSK1" },
  { hanzi: "多少", pinyin: "duō shao", meaning: "how much", level: "HSK1" },
  { hanzi: "儿子", pinyin: "ér zi", meaning: "son", level: "HSK1" },
  { hanzi: "二", pinyin: "èr", meaning: "two", level: "HSK1" },
  { hanzi: "饭店", pinyin: "fàn diàn", meaning: "restaurant", level: "HSK1" },
  { hanzi: "飞机", pinyin: "fēi jī", meaning: "airplane", level: "HSK1" },
  { hanzi: "分钟", pinyin: "fēn zhōng", meaning: "minute", level: "HSK1" },
  { hanzi: "高兴", pinyin: "gāo xìng", meaning: "happy", level: "HSK1" },
  { hanzi: "个", pinyin: "gè", meaning: "general measure word", level: "HSK1" },
  { hanzi: "工作", pinyin: "gōng zuò", meaning: "work", level: "HSK1" },
  { hanzi: "狗", pinyin: "gǒu", meaning: "dog", level: "HSK1" },
  { hanzi: "汉语", pinyin: "hàn yǔ", meaning: "Chinese language", level: "HSK1" },
  { hanzi: "好", pinyin: "hǎo", meaning: "good", level: "HSK1" },
  { hanzi: "号", pinyin: "hào", meaning: "date / number", level: "HSK1" },
  { hanzi: "喝", pinyin: "hē", meaning: "drink", level: "HSK1" },
  { hanzi: "和", pinyin: "hé", meaning: "and", level: "HSK1" },
  { hanzi: "很", pinyin: "hěn", meaning: "very", level: "HSK1" },
  { hanzi: "后面", pinyin: "hòu miàn", meaning: "behind", level: "HSK1" },
  { hanzi: "回", pinyin: "huí", meaning: "return", level: "HSK1" },
  { hanzi: "会", pinyin: "huì", meaning: "can / will", level: "HSK1" },
  { hanzi: "几", pinyin: "jǐ", meaning: "how many", level: "HSK1" },
  { hanzi: "家", pinyin: "jiā", meaning: "home / family", level: "HSK1" },
  { hanzi: "叫", pinyin: "jiào", meaning: "be called", level: "HSK1" },
  { hanzi: "今天", pinyin: "jīn tiān", meaning: "today", level: "HSK1" },
  { hanzi: "九", pinyin: "jiǔ", meaning: "nine", level: "HSK1" },
  { hanzi: "开", pinyin: "kāi", meaning: "open", level: "HSK1" },
  { hanzi: "看", pinyin: "kàn", meaning: "look", level: "HSK1" },
  { hanzi: "看见", pinyin: "kàn jiàn", meaning: "see", level: "HSK1" },
  { hanzi: "块", pinyin: "kuài", meaning: "yuan (money)", level: "HSK1" },
  { hanzi: "来", pinyin: "lái", meaning: "come", level: "HSK1" },
  { hanzi: "老师", pinyin: "lǎo shī", meaning: "teacher", level: "HSK1" },
  { hanzi: "了", pinyin: "le", meaning: "particle", level: "HSK1" },
  { hanzi: "冷", pinyin: "lěng", meaning: "cold", level: "HSK1" },
  { hanzi: "里", pinyin: "lǐ", meaning: "inside", level: "HSK1" },
  { hanzi: "零", pinyin: "líng", meaning: "zero", level: "HSK1" },
  { hanzi: "六", pinyin: "liù", meaning: "six", level: "HSK1" },
  { hanzi: "妈妈", pinyin: "mā ma", meaning: "mother", level: "HSK1" },
  { hanzi: "吗", pinyin: "ma", meaning: "question particle", level: "HSK1" },
  { hanzi: "买", pinyin: "mǎi", meaning: "buy", level: "HSK1" },
  { hanzi: "猫", pinyin: "māo", meaning: "cat", level: "HSK1" },
  { hanzi: "没", pinyin: "méi", meaning: "not have", level: "HSK1" },
  { hanzi: "没关系", pinyin: "méi guān xi", meaning: "it's okay", level: "HSK1" },
  { hanzi: "米饭", pinyin: "mǐ fàn", meaning: "rice", level: "HSK1" },
  { hanzi: "明天", pinyin: "míng tiān", meaning: "tomorrow", level: "HSK1" },
  { hanzi: "名字", pinyin: "míng zi", meaning: "name", level: "HSK1" },
  { hanzi: "哪", pinyin: "nǎ", meaning: "which", level: "HSK1" },
  { hanzi: "那", pinyin: "nà", meaning: "that", level: "HSK1" },
  { hanzi: "呢", pinyin: "ne", meaning: "particle", level: "HSK1" },
  { hanzi: "能", pinyin: "néng", meaning: "can", level: "HSK1" },
  { hanzi: "你", pinyin: "nǐ", meaning: "you", level: "HSK1" },
  { hanzi: "年", pinyin: "nián", meaning: "year", level: "HSK1" },
  { hanzi: "女儿", pinyin: "nǚ ér", meaning: "daughter", level: "HSK1" },
  { hanzi: "朋友", pinyin: "péng you", meaning: "friend", level: "HSK1" },
  { hanzi: "漂亮", pinyin: "piào liang", meaning: "pretty", level: "HSK1" },
  { hanzi: "苹果", pinyin: "píng guǒ", meaning: "apple", level: "HSK1" },
  { hanzi: "七", pinyin: "qī", meaning: "seven", level: "HSK1" },
  { hanzi: "钱", pinyin: "qián", meaning: "money", level: "HSK1" },
  { hanzi: "前面", pinyin: "qián miàn", meaning: "front", level: "HSK1" },
  { hanzi: "请", pinyin: "qǐng", meaning: "please", level: "HSK1" },
  { hanzi: "去", pinyin: "qù", meaning: "go", level: "HSK1" },
  { hanzi: "热", pinyin: "rè", meaning: "hot", level: "HSK1" },
  { hanzi: "人", pinyin: "rén", meaning: "person", level: "HSK1" },
  { hanzi: "认识", pinyin: "rèn shi", meaning: "know", level: "HSK1" },
  { hanzi: "三", pinyin: "sān", meaning: "three", level: "HSK1" },
  { hanzi: "商店", pinyin: "shāng diàn", meaning: "shop", level: "HSK1" },
  { hanzi: "上", pinyin: "shàng", meaning: "up", level: "HSK1" },
  { hanzi: "上午", pinyin: "shàng wǔ", meaning: "morning", level: "HSK1" },
  { hanzi: "少", pinyin: "shǎo", meaning: "few", level: "HSK1" },
  { hanzi: "谁", pinyin: "shéi", meaning: "who", level: "HSK1" },
  { hanzi: "什么", pinyin: "shén me", meaning: "what", level: "HSK1" },
  { hanzi: "十", pinyin: "shí", meaning: "ten", level: "HSK1" },
  { hanzi: "时候", pinyin: "shí hou", meaning: "time", level: "HSK1" },
  { hanzi: "是", pinyin: "shì", meaning: "to be", level: "HSK1" },
  { hanzi: "书", pinyin: "shū", meaning: "book", level: "HSK1" },
  { hanzi: "水", pinyin: "shuǐ", meaning: "water", level: "HSK1" },
  { hanzi: "水果", pinyin: "shuǐ guǒ", meaning: "fruit", level: "HSK1" },
  { hanzi: "睡觉", pinyin: "shuì jiào", meaning: "sleep", level: "HSK1" },
  { hanzi: "说", pinyin: "shuō", meaning: "speak", level: "HSK1" },
  { hanzi: "四", pinyin: "sì", meaning: "four", level: "HSK1" },
  { hanzi: "岁", pinyin: "suì", meaning: "years old", level: "HSK1" },
  { hanzi: "他", pinyin: "tā", meaning: "he", level: "HSK1" },
  { hanzi: "她", pinyin: "tā", meaning: "she", level: "HSK1" },
  { hanzi: "太", pinyin: "tài", meaning: "too", level: "HSK1" },
  { hanzi: "天气", pinyin: "tiān qì", meaning: "weather", level: "HSK1" },
  { hanzi: "听", pinyin: "tīng", meaning: "listen", level: "HSK1" },
  { hanzi: "同学", pinyin: "tóng xué", meaning: "classmate", level: "HSK1" },
  { hanzi: "喂", pinyin: "wèi", meaning: "hello (phone)", level: "HSK1" },
  { hanzi: "我", pinyin: "wǒ", meaning: "I / me", level: "HSK1" },
  { hanzi: "我们", pinyin: "wǒ men", meaning: "we", level: "HSK1" },
  { hanzi: "五", pinyin: "wǔ", meaning: "five", level: "HSK1" },
  { hanzi: "喜欢", pinyin: "xǐ huān", meaning: "like", level: "HSK1" },
  { hanzi: "下", pinyin: "xià", meaning: "down", level: "HSK1" },
  { hanzi: "下午", pinyin: "xià wǔ", meaning: "afternoon", level: "HSK1" },
  { hanzi: "下雨", pinyin: "xià yǔ", meaning: "rain", level: "HSK1" },
  { hanzi: "先生", pinyin: "xiān sheng", meaning: "Mr.", level: "HSK1" },
  { hanzi: "现在", pinyin: "xiàn zài", meaning: "now", level: "HSK1" },
  { hanzi: "想", pinyin: "xiǎng", meaning: "want / think", level: "HSK1" },
  { hanzi: "小", pinyin: "xiǎo", meaning: "small", level: "HSK1" },
  { hanzi: "小姐", pinyin: "xiǎo jiě", meaning: "Miss", level: "HSK1" },
  { hanzi: "些", pinyin: "xiē", meaning: "some", level: "HSK1" },
  { hanzi: "写", pinyin: "xiě", meaning: "write", level: "HSK1" },
  { hanzi: "谢谢", pinyin: "xiè xie", meaning: "thank you", level: "HSK1" },
  { hanzi: "星期", pinyin: "xīng qī", meaning: "week", level: "HSK1" },
  { hanzi: "学生", pinyin: "xué sheng", meaning: "student", level: "HSK1" },
  { hanzi: "学习", pinyin: "xué xí", meaning: "study", level: "HSK1" },
  { hanzi: "学校", pinyin: "xué xiào", meaning: "school", level: "HSK1" },
  { hanzi: "一", pinyin: "yī", meaning: "one", level: "HSK1" },
  { hanzi: "衣服", pinyin: "yī fu", meaning: "clothes", level: "HSK1" },
  { hanzi: "医生", pinyin: "yī shēng", meaning: "doctor", level: "HSK1" },
  { hanzi: "医院", pinyin: "yī yuàn", meaning: "hospital", level: "HSK1" },
  { hanzi: "椅子", pinyin: "yǐ zi", meaning: "chair", level: "HSK1" },
  { hanzi: "有", pinyin: "yǒu", meaning: "have", level: "HSK1" },
  { hanzi: "月", pinyin: "yuè", meaning: "month", level: "HSK1" },
  { hanzi: "在", pinyin: "zài", meaning: "at / in", level: "HSK1" },
  { hanzi: "再见", pinyin: "zài jiàn", meaning: "goodbye", level: "HSK1" },
  { hanzi: "怎么", pinyin: "zěn me", meaning: "how", level: "HSK1" },
  { hanzi: "怎么样", pinyin: "zěn me yàng", meaning: "how about", level: "HSK1" },
  { hanzi: "这", pinyin: "zhè", meaning: "this", level: "HSK1" },
  { hanzi: "中国", pinyin: "zhōng guó", meaning: "China", level: "HSK1" },
  { hanzi: "中午", pinyin: "zhōng wǔ", meaning: "noon", level: "HSK1" },
  { hanzi: "住", pinyin: "zhù", meaning: "live", level: "HSK1" },
  { hanzi: "桌子", pinyin: "zhuō zi", meaning: "table", level: "HSK1" },
  { hanzi: "字", pinyin: "zì", meaning: "character", level: "HSK1" },
  { hanzi: "昨天", pinyin: "zuó tiān", meaning: "yesterday", level: "HSK1" },
  { hanzi: "做", pinyin: "zuò", meaning: "do", level: "HSK1" },

  // HSK 2 (continuation — shortened here due to length)
  { hanzi: "吧", pinyin: "ba", meaning: "particle (suggestion)", level: "HSK2" },
  { hanzi: "白", pinyin: "bái", meaning: "white", level: "HSK2" },
  { hanzi: "百", pinyin: "bǎi", meaning: "hundred", level: "HSK2" },
  { hanzi: "帮助", pinyin: "bāng zhù", meaning: "help", level: "HSK2" },
  { hanzi: "报纸", pinyin: "bào zhǐ", meaning: "newspaper", level: "HSK2" },
  { hanzi: "比", pinyin: "bǐ", meaning: "compare", level: "HSK2" },
  { hanzi: "别", pinyin: "bié", meaning: "don't", level: "HSK2" },
  { hanzi: "长", pinyin: "cháng", meaning: "long", level: "HSK2" },
  { hanzi: "唱歌", pinyin: "chàng gē", meaning: "sing", level: "HSK2" },
  { hanzi: "出", pinyin: "chū", meaning: "go out", level: "HSK2" },
  { hanzi: "穿", pinyin: "chuān", meaning: "wear", level: "HSK2" },
  { hanzi: "次", pinyin: "cì", meaning: "time (measure)", level: "HSK2" },
  { hanzi: "从", pinyin: "cóng", meaning: "from", level: "HSK2" },
  { hanzi: "错", pinyin: "cuò", meaning: "wrong", level: "HSK2" },
  { hanzi: "打篮球", pinyin: "dǎ lán qiú", meaning: "play basketball", level: "HSK2" },
  { hanzi: "大家", pinyin: "dà jiā", meaning: "everyone", level: "HSK2" },
  { hanzi: "到", pinyin: "dào", meaning: "arrive", level: "HSK2" },
  { hanzi: "得", pinyin: "de", meaning: "complement particle", level: "HSK2" },
  { hanzi: "等", pinyin: "děng", meaning: "wait", level: "HSK2" },
  { hanzi: "懂", pinyin: "dǒng", meaning: "understand", level: "HSK2" },
  { hanzi: "对", pinyin: "duì", meaning: "correct", level: "HSK2" },
  { hanzi: "房间", pinyin: "fáng jiān", meaning: "room", level: "HSK2" },
  { hanzi: "非常", pinyin: "fēi cháng", meaning: "very", level: "HSK2" },
  { hanzi: "服务员", pinyin: "fú wù yuán", meaning: "waiter", level: "HSK2" },
  { hanzi: "告诉", pinyin: "gào su", meaning: "tell", level: "HSK2" },
  { hanzi: "哥哥", pinyin: "gē ge", meaning: "older brother", level: "HSK2" },
  { hanzi: "给", pinyin: "gěi", meaning: "give", level: "HSK2" },
  { hanzi: "公共汽车", pinyin: "gōng gòng qì chē", meaning: "bus", level: "HSK2" },
  { hanzi: "公司", pinyin: "gōng sī", meaning: "company", level: "HSK2" },
  { hanzi: "贵", pinyin: "guì", meaning: "expensive", level: "HSK2" },

  // ... (continues up to full ~300 words)
];