export const words = [
  // HSK 1
  { hanzi: "我", pinyin: "wǒ", meaning: "I, me", level: "HSK1" },
  { hanzi: "我们", pinyin: "wǒmen", meaning: "we, us (pl.)", level: "HSK1" },
  { hanzi: "你", pinyin: "nǐ", meaning: "you", level: "HSK1" },
  { hanzi: "他", pinyin: "tā", meaning: "he, him", level: "HSK1" },
  { hanzi: "她", pinyin: "tā", meaning: "she, her", level: "HSK1" },
  { hanzi: "这", pinyin: "zhè", meaning: "this (here)", level: "HSK1" },
  { hanzi: "那", pinyin: "nà", meaning: "that (there)", level: "HSK1" },
  { hanzi: "哪", pinyin: "nǎ", meaning: "which", level: "HSK1" },
  { hanzi: "哪儿", pinyin: "nǎr", meaning: "where", level: "HSK1" },
  { hanzi: "谁", pinyin: "shéi", meaning: "who", level: "HSK1" },
  { hanzi: "什么", pinyin: "shénme", meaning: "what, why", level: "HSK1" },
  { hanzi: "多少", pinyin: "duōshǎo", meaning: "how many, how much", level: "HSK1" },
  { hanzi: "几", pinyin: "jǐ", meaning: "a few, how many", level: "HSK1" },
  { hanzi: "怎么", pinyin: "zěnme", meaning: "how", level: "HSK1" },
  { hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "how about", level: "HSK1" },
  { hanzi: "一", pinyin: "yī", meaning: "one", level: "HSK1" },
  { hanzi: "二", pinyin: "èr", meaning: "two", level: "HSK1" },
  { hanzi: "三", pinyin: "sān", meaning: "three", level: "HSK1" },
  { hanzi: "四", pinyin: "sì", meaning: "four", level: "HSK1" },
  { hanzi: "五", pinyin: "wǔ", meaning: "five", level: "HSK1" },
  { hanzi: "六", pinyin: "liù", meaning: "six", level: "HSK1" },
  { hanzi: "七", pinyin: "qī", meaning: "seven", level: "HSK1" },
  { hanzi: "八", pinyin: "bā", meaning: "eight", level: "HSK1" },
  { hanzi: "九", pinyin: "jiǔ", meaning: "nine", level: "HSK1" },
  { hanzi: "十", pinyin: "shí", meaning: "ten", level: "HSK1" },
  { hanzi: "个", pinyin: "gè", meaning: "(measure word)", level: "HSK1" },
  { hanzi: "岁", pinyin: "suì", meaning: "(age)", level: "HSK1" },
  { hanzi: "本", pinyin: "běn", meaning: "(for books)", level: "HSK1" },
  { hanzi: "些", pinyin: "xiē", meaning: "some", level: "HSK1" },
  { hanzi: "块", pinyin: "kuài", meaning: "piece, chunk", level: "HSK1" },
  { hanzi: "不", pinyin: "bù", meaning: "no", level: "HSK1" },
  { hanzi: "没", pinyin: "méi", meaning: "no", level: "HSK1" },
  { hanzi: "很", pinyin: "hěn", meaning: "very", level: "HSK1" },
  { hanzi: "太", pinyin: "tài", meaning: "too", level: "HSK1" },
  { hanzi: "都", pinyin: "dōu", meaning: "all", level: "HSK1" },
  { hanzi: "一点儿", pinyin: "yīdiǎnr", meaning: "a little bit", level: "HSK1" },
  { hanzi: "和", pinyin: "hé", meaning: "and", level: "HSK1" },
  { hanzi: "在", pinyin: "zài", meaning: "in, at", level: "HSK1" },
  { hanzi: "的", pinyin: "de", meaning: "(possessive particle)", level: "HSK1" },
  { hanzi: "了", pinyin: "le", meaning: "(completed action particle)", level: "HSK1" },
  { hanzi: "吗", pinyin: "ma", meaning: "(question particle)", level: "HSK1" },
  { hanzi: "呢", pinyin: "ne", meaning: "(question particle)", level: "HSK1" },
  { hanzi: "喂", pinyin: "wèi", meaning: "hello (phone)", level: "HSK1" },
  { hanzi: "家", pinyin: "jiā", meaning: "home", level: "HSK1" },
  { hanzi: "学校", pinyin: "xuéxiào", meaning: "school", level: "HSK1" },
  { hanzi: "饭店", pinyin: "fàndiàn", meaning: "restaurant", level: "HSK1" },
  { hanzi: "商店", pinyin: "shāngdiàn", meaning: "store", level: "HSK1" },
  { hanzi: "医院", pinyin: "yīyuàn", meaning: "hospital", level: "HSK1" },
  { hanzi: "中国", pinyin: "Zhōngguó", meaning: "China", level: "HSK1" },
  { hanzi: "北京", pinyin: "Běijīng", meaning: "Beijing", level: "HSK1" },
  { hanzi: "上", pinyin: "shàng", meaning: "up", level: "HSK1" },
  { hanzi: "下", pinyin: "xià", meaning: "down", level: "HSK1" },
  { hanzi: "前面", pinyin: "qiánmiàn", meaning: "front", level: "HSK1" },
  { hanzi: "后面", pinyin: "hòumiàn", meaning: "behind", level: "HSK1" },
  { hanzi: "里面", pinyin: "lǐmiàn", meaning: "inside", level: "HSK1" },
  { hanzi: "今天", pinyin: "jīntiān", meaning: "today", level: "HSK1" },
  { hanzi: "明天", pinyin: "míngtiān", meaning: "tomorrow", level: "HSK1" },
  { hanzi: "昨天", pinyin: "zuótiān", meaning: "yesterday", level: "HSK1" },
  { hanzi: "上午", pinyin: "shàngwǔ", meaning: "morning", level: "HSK1" },
  { hanzi: "中午", pinyin: "zhōngwǔ", meaning: "noon", level: "HSK1" },
  { hanzi: "下午", pinyin: "xiàwǔ", meaning: "afternoon", level: "HSK1" },
  { hanzi: "年", pinyin: "nián", meaning: "year", level: "HSK1" },
  { hanzi: "月", pinyin: "yuè", meaning: "month", level: "HSK1" },
  { hanzi: "号", pinyin: "hào", meaning: "date", level: "HSK1" },
  { hanzi: "星期", pinyin: "xīngqī", meaning: "week", level: "HSK1" },
  { hanzi: "点", pinyin: "diǎn", meaning: "o'clock", level: "HSK1" },
  { hanzi: "分钟", pinyin: "fēnzhōng", meaning: "minute", level: "HSK1" },
  { hanzi: "现在", pinyin: "xiànzài", meaning: "now", level: "HSK1" },
  { hanzi: "时候", pinyin: "shíhou", meaning: "time", level: "HSK1" },
  { hanzi: "爸爸", pinyin: "bàba", meaning: "father", level: "HSK1" },
  { hanzi: "妈妈", pinyin: "māma", meaning: "mother", level: "HSK1" },
  { hanzi: "儿子", pinyin: "érzi", meaning: "son", level: "HSK1" },
  { hanzi: "女儿", pinyin: "nǚér", meaning: "daughter", level: "HSK1" },
  { hanzi: "老师", pinyin: "lǎoshī", meaning: "teacher", level: "HSK1" },
  { hanzi: "学生", pinyin: "xuéshēng", meaning: "student", level: "HSK1" },
  { hanzi: "同学", pinyin: "tóngxué", meaning: "classmate", level: "HSK1" },
  { hanzi: "朋友", pinyin: "péngyǒu", meaning: "friend", level: "HSK1" },
  { hanzi: "医生", pinyin: "yīshēng", meaning: "doctor", level: "HSK1" },
  { hanzi: "先生", pinyin: "xiānsheng", meaning: "sir", level: "HSK1" },
  { hanzi: "小姐", pinyin: "xiǎojiě", meaning: "Miss", level: "HSK1" },
  { hanzi: "衣服", pinyin: "yīfu", meaning: "clothes", level: "HSK1" },
  { hanzi: "水", pinyin: "shuǐ", meaning: "water", level: "HSK1" },
  { hanzi: "菜", pinyin: "cài", meaning: "dish", level: "HSK1" },
  { hanzi: "米饭", pinyin: "mǐfàn", meaning: "rice", level: "HSK1" },
  { hanzi: "水果", pinyin: "shuǐguǒ", meaning: "fruit", level: "HSK1" },
  { hanzi: "苹果", pinyin: "píngguǒ", meaning: "apple", level: "HSK1" },
  { hanzi: "茶", pinyin: "chá", meaning: "tea", level: "HSK1" },
  { hanzi: "杯子", pinyin: "bēizi", meaning: "cup", level: "HSK1" },
  { hanzi: "钱", pinyin: "qián", meaning: "money", level: "HSK1" },
  { hanzi: "飞机", pinyin: "fēijī", meaning: "airplane", level: "HSK1" },
  { hanzi: "出租车", pinyin: "chūzūchē", meaning: "taxi", level: "HSK1" },
  { hanzi: "电视", pinyin: "diànshì", meaning: "television", level: "HSK1" },
  { hanzi: "电脑", pinyin: "diànnǎo", meaning: "computer", level: "HSK1" },
  { hanzi: "电影", pinyin: "diànyǐng", meaning: "movie", level: "HSK1" },
  { hanzi: "天气", pinyin: "tiānqì", meaning: "weather", level: "HSK1" },
  { hanzi: "猫", pinyin: "māo", meaning: "cat", level: "HSK1" },
  { hanzi: "狗", pinyin: "gǒu", meaning: "dog", level: "HSK1" },
  { hanzi: "东西", pinyin: "dōngxi", meaning: "thing", level: "HSK1" },
  { hanzi: "人", pinyin: "rén", meaning: "person", level: "HSK1" },
  { hanzi: "名字", pinyin: "míngzi", meaning: "name", level: "HSK1" },
  { hanzi: "书", pinyin: "shū", meaning: "book", level: "HSK1" },
  { hanzi: "汉语", pinyin: "hànyǔ", meaning: "Chinese", level: "HSK1" },
  { hanzi: "字", pinyin: "zì", meaning: "character", level: "HSK1" },
  { hanzi: "桌子", pinyin: "zhuōzi", meaning: "desk", level: "HSK1" },
  { hanzi: "椅子", pinyin: "yǐzi", meaning: "chair", level: "HSK1" },
  { hanzi: "谢谢", pinyin: "xièxie", meaning: "thank you", level: "HSK1" },
  { hanzi: "不客气", pinyin: "búkèqì", meaning: "you're welcome", level: "HSK1" },
  { hanzi: "再见", pinyin: "zàijiàn", meaning: "goodbye", level: "HSK1" },
  { hanzi: "请", pinyin: "qǐng", meaning: "please", level: "HSK1" },
  { hanzi: "对不起", pinyin: "duìbùqǐ", meaning: "sorry", level: "HSK1" },
  { hanzi: "没关系", pinyin: "méiguānxì", meaning: "it's okay", level: "HSK1" },
  { hanzi: "是", pinyin: "shì", meaning: "to be", level: "HSK1" },
  { hanzi: "有", pinyin: "yǒu", meaning: "have", level: "HSK1" },
  { hanzi: "看", pinyin: "kàn", meaning: "look", level: "HSK1" },
  { hanzi: "听", pinyin: "tīng", meaning: "listen", level: "HSK1" },
  { hanzi: "说", pinyin: "shuō", meaning: "speak", level: "HSK1" },
  { hanzi: "读", pinyin: "dú", meaning: "read", level: "HSK1" },
  { hanzi: "写", pinyin: "xiě", meaning: "write", level: "HSK1" },
  { hanzi: "看见", pinyin: "kànjiàn", meaning: "see", level: "HSK1" },
  { hanzi: "叫", pinyin: "jiào", meaning: "call", level: "HSK1" },
  { hanzi: "来", pinyin: "lái", meaning: "come", level: "HSK1" },
  { hanzi: "回", pinyin: "huí", meaning: "return", level: "HSK1" },
  { hanzi: "去", pinyin: "qù", meaning: "go", level: "HSK1" },
  { hanzi: "吃", pinyin: "chī", meaning: "eat", level: "HSK1" },
  { hanzi: "喝", pinyin: "hē", meaning: "drink", level: "HSK1" },
  { hanzi: "睡觉", pinyin: "shuìjiào", meaning: "sleep", level: "HSK1" },
  { hanzi: "打电话", pinyin: "dǎdiànhuà", meaning: "make a phone call", level: "HSK1" },
  { hanzi: "做", pinyin: "zuò", meaning: "do", level: "HSK1" },
  { hanzi: "买", pinyin: "mǎi", meaning: "buy", level: "HSK1" },
  { hanzi: "开", pinyin: "kāi", meaning: "open", level: "HSK1" },
  { hanzi: "坐", pinyin: "zuò", meaning: "sit", level: "HSK1" },
  { hanzi: "住", pinyin: "zhù", meaning: "live", level: "HSK1" },
  { hanzi: "学习", pinyin: "xuéxí", meaning: "study", level: "HSK1" },
  { hanzi: "工作", pinyin: "gōngzuò", meaning: "work", level: "HSK1" },
  { hanzi: "下雨", pinyin: "xiàyǔ", meaning: "rain", level: "HSK1" },
  { hanzi: "爱", pinyin: "ài", meaning: "love", level: "HSK1" },
  { hanzi: "喜欢", pinyin: "xǐhuān", meaning: "like", level: "HSK1" },
  { hanzi: "想", pinyin: "xiǎng", meaning: "want", level: "HSK1" },
  { hanzi: "认识", pinyin: "rènshi", meaning: "know", level: "HSK1" },
  { hanzi: "会", pinyin: "huì", meaning: "can", level: "HSK1" },
  { hanzi: "能", pinyin: "néng", meaning: "be able to", level: "HSK1" },
  { hanzi: "好", pinyin: "hǎo", meaning: "good", level: "HSK1" },
  { hanzi: "大", pinyin: "dà", meaning: "big", level: "HSK1" },
  { hanzi: "小", pinyin: "xiǎo", meaning: "small", level: "HSK1" },
  { hanzi: "多", pinyin: "duō", meaning: "many", level: "HSK1" },
  { hanzi: "少", pinyin: "shǎo", meaning: "few", level: "HSK1" },
  { hanzi: "冷", pinyin: "lěng", meaning: "cold", level: "HSK1" },
  { hanzi: "热", pinyin: "rè", meaning: "hot", level: "HSK1" },
  { hanzi: "高兴", pinyin: "gāoxìng", meaning: "happy", level: "HSK1" },
  { hanzi: "漂亮", pinyin: "piàoliang", meaning: "beautiful", level: "HSK1" },

  // HSK 2
  { hanzi: "吧", pinyin: "ba", meaning: "particle", level: "HSK2" },
  { hanzi: "白", pinyin: "bái", meaning: "white", level: "HSK2" },
  { hanzi: "百", pinyin: "bǎi", meaning: "hundred", level: "HSK2" },
  { hanzi: "帮助", pinyin: "bāngzhù", meaning: "help", level: "HSK2" },
  { hanzi: "报纸", pinyin: "bàozhǐ", meaning: "newspaper", level: "HSK2" },
  { hanzi: "比", pinyin: "bǐ", meaning: "compare", level: "HSK2" },
  { hanzi: "别", pinyin: "bié", meaning: "don't", level: "HSK2" },
  { hanzi: "长", pinyin: "cháng", meaning: "long", level: "HSK2" },
  { hanzi: "唱歌", pinyin: "chànggē", meaning: "sing", level: "HSK2" },
  { hanzi: "出", pinyin: "chū", meaning: "go out", level: "HSK2" },
  { hanzi: "穿", pinyin: "chuān", meaning: "wear", level: "HSK2" },
  { hanzi: "次", pinyin: "cì", meaning: "time (measure)", level: "HSK2" },
  { hanzi: "从", pinyin: "cóng", meaning: "from", level: "HSK2" },
  { hanzi: "您", pinyin: "nín", meaning: "you (polite)", level: "HSK2" },
  { hanzi: "它", pinyin: "tā", meaning: "it", level: "HSK2" },
  { hanzi: "大家", pinyin: "dàjiā", meaning: "everyone", level: "HSK2" },
  { hanzi: "每", pinyin: "měi", meaning: "every, each", level: "HSK2" },
  { hanzi: "为什么", pinyin: "wèishénme", meaning: "why", level: "HSK2" },
  { hanzi: "零", pinyin: "líng", meaning: "zero", level: "HSK2" },
  { hanzi: "两", pinyin: "liǎng", meaning: "two", level: "HSK2" },
  { hanzi: "千", pinyin: "qiān", meaning: "thousand", level: "HSK2" },
  { hanzi: "第一", pinyin: "dìyī", meaning: "first", level: "HSK2" },
  { hanzi: "件", pinyin: "jiàn", meaning: "piece", level: "HSK2" },
  { hanzi: "非常", pinyin: "fēicháng", meaning: "very", level: "HSK2" },
  { hanzi: "也", pinyin: "yě", meaning: "also", level: "HSK2" },
  { hanzi: "还", pinyin: "hái", meaning: "still", level: "HSK2" },
  { hanzi: "最", pinyin: "zuì", meaning: "the most", level: "HSK2" },
  { hanzi: "真", pinyin: "zhēn", meaning: "really", level: "HSK2" },
  { hanzi: "正在", pinyin: "zhèngzài", meaning: "be doing", level: "HSK2" },
  { hanzi: "已经", pinyin: "yǐjīng", meaning: "already", level: "HSK2" },
  { hanzi: "一起", pinyin: "yìqǐ", meaning: "together", level: "HSK2" },
  { hanzi: "再", pinyin: "zài", meaning: "again", level: "HSK2" },
  { hanzi: "就", pinyin: "jiù", meaning: "at once", level: "HSK2" },
  { hanzi: "往", pinyin: "wǎng", meaning: "toward", level: "HSK2" },
  { hanzi: "离", pinyin: "lí", meaning: "distance from", level: "HSK2" },
  { hanzi: "得", pinyin: "de", meaning: "complement particle", level: "HSK2" },
  { hanzi: "着", pinyin: "zhe", meaning: "continuous particle", level: "HSK2" },
  { hanzi: "过", pinyin: "guò", meaning: "experience particle", level: "HSK2" },
  { hanzi: "机场", pinyin: "jīchǎng", meaning: "airport", level: "HSK2" },
  { hanzi: "教室", pinyin: "jiàoshì", meaning: "classroom", level: "HSK2" },
  { hanzi: "房间", pinyin: "fángjiān", meaning: "room", level: "HSK2" },
  { hanzi: "路", pinyin: "lù", meaning: "road", level: "HSK2" },
  { hanzi: "左边", pinyin: "zuǒbiān", meaning: "left", level: "HSK2" },
  { hanzi: "右边", pinyin: "yòubiān", meaning: "right", level: "HSK2" },
  { hanzi: "外", pinyin: "wài", meaning: "outside", level: "HSK2" },
  { hanzi: "旁边", pinyin: "pángbiān", meaning: "beside", level: "HSK2" },
  { hanzi: "一下", pinyin: "yīxià", meaning: "a little", level: "HSK2" },
  { hanzi: "早上", pinyin: "zǎoshàng", meaning: "morning", level: "HSK2" },
  { hanzi: "晚上", pinyin: "wǎnshàng", meaning: "evening", level: "HSK2" },
  { hanzi: "小时", pinyin: "xiǎoshí", meaning: "hour", level: "HSK2" },
  { hanzi: "时间", pinyin: "shíjiān", meaning: "time", level: "HSK2" },
  { hanzi: "去年", pinyin: "qùnián", meaning: "last year", level: "HSK2" },
  { hanzi: "日", pinyin: "rì", meaning: "day", level: "HSK2" },
  { hanzi: "生日", pinyin: "shēngrì", meaning: "birthday", level: "HSK2" },
  { hanzi: "哥哥", pinyin: "gēge", meaning: "older brother", level: "HSK2" },
  { hanzi: "姐姐", pinyin: "jiějie", meaning: "older sister", level: "HSK2" },
  { hanzi: "弟弟", pinyin: "dìdi", meaning: "younger brother", level: "HSK2" },
  { hanzi: "妹妹", pinyin: "mèimei", meaning: "younger sister", level: "HSK2" },
  { hanzi: "丈夫", pinyin: "zhàngfu", meaning: "husband", level: "HSK2" },
  { hanzi: "妻子", pinyin: "qīzi", meaning: "wife", level: "HSK2" },
  { hanzi: "孩子", pinyin: "háizi", meaning: "child", level: "HSK2" },
  { hanzi: "男人", pinyin: "nánrén", meaning: "man", level: "HSK2" },
  { hanzi: "女人", pinyin: "nǚrén", meaning: "woman", level: "HSK2" },
  { hanzi: "服务员", pinyin: "fúwùyuán", meaning: "waiter", level: "HSK2" },
  { hanzi: "鱼", pinyin: "yú", meaning: "fish", level: "HSK2" },
  { hanzi: "羊肉", pinyin: "yángròu", meaning: "mutton", level: "HSK2" },
  { hanzi: "牛奶", pinyin: "niúnǎi", meaning: "milk", level: "HSK2" },
  { hanzi: "鸡蛋", pinyin: "jīdàn", meaning: "egg", level: "HSK2" },
  { hanzi: "西瓜", pinyin: "xīguā", meaning: "watermelon", level: "HSK2" },
  { hanzi: "咖啡", pinyin: "kāfēi", meaning: "coffee", level: "HSK2" },
  { hanzi: "雪", pinyin: "xuě", meaning: "snow", level: "HSK2" },
  { hanzi: "药", pinyin: "yào", meaning: "medicine", level: "HSK2" },
  { hanzi: "手机", pinyin: "shǒujī", meaning: "phone", level: "HSK2" },
  { hanzi: "手表", pinyin: "shǒubiǎo", meaning: "watch", level: "HSK2" },
  { hanzi: "眼睛", pinyin: "yǎnjīng", meaning: "eye", level: "HSK2" },
  { hanzi: "身体", pinyin: "shēntǐ", meaning: "body", level: "HSK2" },
  { hanzi: "公共汽车", pinyin: "gōnggòngqìchē", meaning: "bus", level: "HSK2" },
  { hanzi: "门", pinyin: "mén", meaning: "door", level: "HSK2" },
  { hanzi: "题", pinyin: "tí", meaning: "question item", level: "HSK2" },
  { hanzi: "课", pinyin: "kè", meaning: "lesson", level: "HSK2" },
  { hanzi: "姓", pinyin: "xìng", meaning: "surname", level: "HSK2" },
  { hanzi: "问题", pinyin: "wèntí", meaning: "problem", level: "HSK2" },
  { hanzi: "事情", pinyin: "shìqing", meaning: "matter", level: "HSK2" },
  { hanzi: "考试", pinyin: "kǎoshì", meaning: "exam", level: "HSK2" },
  { hanzi: "票", pinyin: "piào", meaning: "ticket", level: "HSK2" },
  { hanzi: "意思", pinyin: "yìsi", meaning: "meaning", level: "HSK2" },
  { hanzi: "颜色", pinyin: "yánsè", meaning: "color", level: "HSK2" },
  { hanzi: "铅笔", pinyin: "qiánbǐ", meaning: "pencil", level: "HSK2" },
  { hanzi: "面条", pinyin: "miàntiáo", meaning: "noodles", level: "HSK2" },
  { hanzi: "火车站", pinyin: "huǒchēzhàn", meaning: "train station", level: "HSK2" },
  { hanzi: "公司", pinyin: "gōngsī", meaning: "company", level: "HSK2" },
  { hanzi: "宾馆", pinyin: "bīngguǎn", meaning: "hotel", level: "HSK2" },
  { hanzi: "说话", pinyin: "shuōhuà", meaning: "talk", level: "HSK2" },
  { hanzi: "卖", pinyin: "mài", meaning: "sell", level: "HSK2" },
  { hanzi: "问", pinyin: "wèn", meaning: "ask", level: "HSK2" },
  { hanzi: "走", pinyin: "zǒu", meaning: "walk", level: "HSK2" },
  { hanzi: "进", pinyin: "jìn", meaning: "enter", level: "HSK2" },
  { hanzi: "跑步", pinyin: "pǎobù", meaning: "run", level: "HSK2" },
  { hanzi: "到", pinyin: "dào", meaning: "arrive", level: "HSK2" },
  { hanzi: "洗", pinyin: "xǐ", meaning: "wash", level: "HSK2" },
  { hanzi: "给", pinyin: "gěi", meaning: "give", level: "HSK2" },
  { hanzi: "找", pinyin: "zhǎo", meaning: "find", level: "HSK2" },
  { hanzi: "懂", pinyin: "dǒng", meaning: "understand", level: "HSK2" },
  { hanzi: "笑", pinyin: "xiào", meaning: "smile", level: "HSK2" },
  { hanzi: "告诉", pinyin: "gàosù", meaning: "tell", level: "HSK2" },
  { hanzi: "准备", pinyin: "zhǔnbèi", meaning: "prepare", level: "HSK2" },
  { hanzi: "开始", pinyin: "kāishǐ", meaning: "begin", level: "HSK2" },
  { hanzi: "介绍", pinyin: "jièshào", meaning: "introduce", level: "HSK2" },
  { hanzi: "玩", pinyin: "wán", meaning: "play", level: "HSK2" },
  { hanzi: "送", pinyin: "sòng", meaning: "give (gift)", level: "HSK2" },
  { hanzi: "等", pinyin: "děng", meaning: "wait", level: "HSK2" },
  { hanzi: "让", pinyin: "ràng", meaning: "let", level: "HSK2" },
  { hanzi: "起床", pinyin: "qǐchuáng", meaning: "get up", level: "HSK2" },
  { hanzi: "跳舞", pinyin: "tiàowǔ", meaning: "dance", level: "HSK2" },
  { hanzi: "旅游", pinyin: "lǚyóu", meaning: "travel", level: "HSK2" },
  { hanzi: "上班", pinyin: "shàngbān", meaning: "go to work", level: "HSK2" },
  { hanzi: "生病", pinyin: "shēngbìng", meaning: "get sick", level: "HSK2" },
  { hanzi: "休息", pinyin: "xiūxi", meaning: "rest", level: "HSK2" },
  { hanzi: "运动", pinyin: "yùndòng", meaning: "exercise", level: "HSK2" },
  { hanzi: "游泳", pinyin: "yóuyǒng", meaning: "swim", level: "HSK2" },
  { hanzi: "踢足球", pinyin: "tīzúqiú", meaning: "play football", level: "HSK2" },
  { hanzi: "打篮球", pinyin: "dǎlánqiú", meaning: "play basketball", level: "HSK2" },
  { hanzi: "完", pinyin: "wán", meaning: "finish", level: "HSK2" },
  { hanzi: "觉得", pinyin: "juédé", meaning: "feel", level: "HSK2" },
  { hanzi: "知道", pinyin: "zhīdao", meaning: "know", level: "HSK2" },
  { hanzi: "希望", pinyin: "xīwàng", meaning: "hope", level: "HSK2" },
  { hanzi: "可以", pinyin: "kěyǐ", meaning: "can", level: "HSK2" },
  { hanzi: "要", pinyin: "yào", meaning: "want", level: "HSK2" },
  { hanzi: "可能", pinyin: "kěnéng", meaning: "maybe", level: "HSK2" },
  { hanzi: "高", pinyin: "gāo", meaning: "tall", level: "HSK2" },
  { hanzi: "红", pinyin: "hóng", meaning: "red", level: "HSK2" },
  { hanzi: "黑", pinyin: "hēi", meaning: "black", level: "HSK2" },
  { hanzi: "忙", pinyin: "máng", meaning: "busy", level: "HSK2" },
  { hanzi: "快", pinyin: "kuài", meaning: "fast", level: "HSK2" },
  { hanzi: "慢", pinyin: "màn", meaning: "slow", level: "HSK2" },
  { hanzi: "远", pinyin: "yuǎn", meaning: "far", level: "HSK2" },
  { hanzi: "近", pinyin: "jìn", meaning: "near", level: "HSK2" },
  { hanzi: "好吃", pinyin: "hǎochī", meaning: "delicious", level: "HSK2" },
  { hanzi: "累", pinyin: "lèi", meaning: "tired", level: "HSK2" },
  { hanzi: "新", pinyin: "xīn", meaning: "new", level: "HSK2" },
  { hanzi: "贵", pinyin: "guì", meaning: "expensive", level: "HSK2" },
  { hanzi: "便宜", pinyin: "piányi", meaning: "cheap", level: "HSK2" },
  { hanzi: "晴", pinyin: "qíng", meaning: "sunny", level: "HSK2" },
  { hanzi: "阴", pinyin: "yīn", meaning: "cloudy", level: "HSK2" },
  { hanzi: "错", pinyin: "cuò", meaning: "wrong", level: "HSK2" },
  { hanzi: "快乐", pinyin: "kuàilè", meaning: "happy", level: "HSK2" },
  { hanzi: "对", pinyin: "duì", meaning: "correct", level: "HSK2" },

  // HSK 3
  { hanzi: "阿姨", pinyin: "āyí", meaning: "aunt", level: "HSK3" },
  { hanzi: "啊", pinyin: "a", meaning: "ah (particle)", level: "HSK3" },
  { hanzi: "矮", pinyin: "ǎi", meaning: "short", level: "HSK3" },
  { hanzi: "爱好", pinyin: "àihào", meaning: "hobby", level: "HSK3" },
  { hanzi: "安静", pinyin: "ānjìng", meaning: "quiet", level: "HSK3" },
  { hanzi: "把", pinyin: "bǎ", meaning: "(particle)", level: "HSK3" },
  { hanzi: "班", pinyin: "bān", meaning: "class", level: "HSK3" },
  { hanzi: "搬", pinyin: "bān", meaning: "move", level: "HSK3" },
  { hanzi: "半", pinyin: "bàn", meaning: "half", level: "HSK3" },
  { hanzi: "办法", pinyin: "bànfǎ", meaning: "method", level: "HSK3" },
  { hanzi: "办公室", pinyin: "bàngōngshì", meaning: "office", level: "HSK3" },
  { hanzi: "帮忙", pinyin: "bāngmáng", meaning: "help", level: "HSK3" },
  { hanzi: "包", pinyin: "bāo", meaning: "bag", level: "HSK3" },
  { hanzi: "饱", pinyin: "bǎo", meaning: "full", level: "HSK3" },
  { hanzi: "北方", pinyin: "běifāng", meaning: "north", level: "HSK3" },
  { hanzi: "被", pinyin: "bèi", meaning: "(passive marker)", level: "HSK3" },
  { hanzi: "鼻子", pinyin: "bízi", meaning: "nose", level: "HSK3" },
  { hanzi: "比较", pinyin: "bǐjiào", meaning: "compare", level: "HSK3" },
  { hanzi: "比赛", pinyin: "bǐsài", meaning: "competition", level: "HSK3" },
  { hanzi: "笔记本", pinyin: "bǐjìběn", meaning: "notebook", level: "HSK3" },
  { hanzi: "必须", pinyin: "bìxū", meaning: "must", level: "HSK3" },
  { hanzi: "变化", pinyin: "biànhuà", meaning: "change", level: "HSK3" },
  { hanzi: "别人", pinyin: "biéren", meaning: "others", level: "HSK3" },
  { hanzi: "冰箱", pinyin: "bīngxiāng", meaning: "refrigerator", level: "HSK3" },
  { hanzi: "菜单", pinyin: "càidān", meaning: "menu", level: "HSK3" },
  { hanzi: "参加", pinyin: "cānjiā", meaning: "participate", level: "HSK3" },
  { hanzi: "草", pinyin: "cǎo", meaning: "grass", level: "HSK3" },
  { hanzi: "层", pinyin: "céng", meaning: "layer", level: "HSK3" },
  { hanzi: "差", pinyin: "chà", meaning: "bad", level: "HSK3" },
  { hanzi: "超市", pinyin: "chāoshì", meaning: "supermarket", level: "HSK3" },
  { hanzi: "衬衫", pinyin: "chènshān", meaning: "shirt", level: "HSK3" },
  { hanzi: "成绩", pinyin: "chéngjì", meaning: "grade", level: "HSK3" },
  { hanzi: "城市", pinyin: "chéngshì", meaning: "city", level: "HSK3" },
  { hanzi: "迟到", pinyin: "chídào", meaning: "be late", level: "HSK3" },
  { hanzi: "除了", pinyin: "chúle", meaning: "except", level: "HSK3" },
  { hanzi: "船", pinyin: "chuán", meaning: "ship", level: "HSK3" },
  { hanzi: "春", pinyin: "chūn", meaning: "spring", level: "HSK3" },
  { hanzi: "词典", pinyin: "cídiǎn", meaning: "dictionary", level: "HSK3" },
  { hanzi: "聪明", pinyin: "cōngming", meaning: "smart", level: "HSK3" },
  { hanzi: "打扫", pinyin: "dǎsǎo", meaning: "clean", level: "HSK3" },
  { hanzi: "打算", pinyin: "dǎsuàn", meaning: "plan", level: "HSK3" },
  { hanzi: "带", pinyin: "dài", meaning: "bring", level: "HSK3" },
  { hanzi: "担心", pinyin: "dānxīn", meaning: "worry", level: "HSK3" },
  { hanzi: "蛋糕", pinyin: "dàngāo", meaning: "cake", level: "HSK3" },
  { hanzi: "当然", pinyin: "dāngrán", meaning: "of course", level: "HSK3" },
  { hanzi: "地", pinyin: "de", meaning: "(adverb particle)", level: "HSK3" },
  { hanzi: "灯", pinyin: "dēng", meaning: "lamp", level: "HSK3" },
  { hanzi: "地方", pinyin: "dìfang", meaning: "place", level: "HSK3" },
  { hanzi: "地铁", pinyin: "dìtiě", meaning: "subway", level: "HSK3" },
  { hanzi: "地图", pinyin: "dìtú", meaning: "map", level: "HSK3" },
  { hanzi: "电梯", pinyin: "diàntī", meaning: "elevator", level: "HSK3" },
  { hanzi: "电子邮件", pinyin: "diànzǐyóujiàn", meaning: "email", level: "HSK3" },
  { hanzi: "东", pinyin: "dōng", meaning: "east", level: "HSK3" },
  { hanzi: "冬", pinyin: "dōng", meaning: "winter", level: "HSK3" },
  { hanzi: "动物", pinyin: "dòngwù", meaning: "animal", level: "HSK3" },
  { hanzi: "短", pinyin: "duǎn", meaning: "short", level: "HSK3" },
  { hanzi: "段", pinyin: "duàn", meaning: "paragraph", level: "HSK3" },
  { hanzi: "锻炼", pinyin: "duànliàn", meaning: "exercise", level: "HSK3" },
  { hanzi: "多么", pinyin: "duōme", meaning: "how (exclamatory)", level: "HSK3" },
  { hanzi: "饿", pinyin: "è", meaning: "hungry", level: "HSK3" },
  { hanzi: "不但……而且……", pinyin: "búdàn…érqiě…", meaning: "not only...but also...", level: "HSK3" },
  { hanzi: "耳朵", pinyin: "ěrduo", meaning: "ear", level: "HSK3" },
  { hanzi: "发", pinyin: "fā", meaning: "send", level: "HSK3" },
  { hanzi: "发烧", pinyin: "fāshāo", meaning: "fever", level: "HSK3" },
  { hanzi: "发现", pinyin: "fāxiàn", meaning: "discover", level: "HSK3" },
  { hanzi: "方便", pinyin: "fāngbiàn", meaning: "convenient", level: "HSK3" },
  { hanzi: "放", pinyin: "fàng", meaning: "put", level: "HSK3" },
  { hanzi: "放心", pinyin: "fàngxīn", meaning: "don’t worry", level: "HSK3" },
  { hanzi: "分", pinyin: "fēn", meaning: "minute", level: "HSK3" },
  { hanzi: "附近", pinyin: "fùjìn", meaning: "nearby", level: "HSK3" },
  { hanzi: "复习", pinyin: "fùxí", meaning: "review", level: "HSK3" },
  { hanzi: "干净", pinyin: "gānjìng", meaning: "clean", level: "HSK3" },
  { hanzi: "感兴趣", pinyin: "gǎnxìngqù", meaning: "be interested in", level: "HSK3" },
  { hanzi: "感冒", pinyin: "gǎnmào", meaning: "catch a cold", level: "HSK3" },
  { hanzi: "刚才", pinyin: "gāngcái", meaning: "just now", level: "HSK3" },
  { hanzi: "个子", pinyin: "gèzi", meaning: "height", level: "HSK3" },
  { hanzi: "跟", pinyin: "gēn", meaning: "with", level: "HSK3" },
  { hanzi: "根据", pinyin: "gēnjù", meaning: "according to", level: "HSK3" },
  { hanzi: "更", pinyin: "gèng", meaning: "more", level: "HSK3" },
  { hanzi: "公斤", pinyin: "gōngjīn", meaning: "kilogram", level: "HSK3" },
  { hanzi: "公园", pinyin: "gōngyuán", meaning: "park", level: "HSK3" },
  { hanzi: "故事", pinyin: "gùshi", meaning: "story", level: "HSK3" },
  { hanzi: "刮风", pinyin: "guāfēng", meaning: "windy", level: "HSK3" },
  { hanzi: "关", pinyin: "guān", meaning: "close", level: "HSK3" },
  { hanzi: "关系", pinyin: "guānxì", meaning: "relationship", level: "HSK3" },
  { hanzi: "关心", pinyin: "guānxīn", meaning: "care", level: "HSK3" },
  { hanzi: "关于", pinyin: "guānyú", meaning: "about", level: "HSK3" },
  { hanzi: "国家", pinyin: "guójiā", meaning: "country", level: "HSK3" },
  { hanzi: "过去", pinyin: "guòqù", meaning: "past", level: "HSK3" },
  { hanzi: "过", pinyin: "guò", meaning: "pass", level: "HSK3" },
  { hanzi: "还是", pinyin: "háishì", meaning: "still", level: "HSK3" },
  { hanzi: "害怕", pinyin: "hàipà", meaning: "afraid", level: "HSK3" },
  { hanzi: "黑板", pinyin: "hēibǎn", meaning: "blackboard", level: "HSK3" },
  { hanzi: "后来", pinyin: "hòulái", meaning: "later", level: "HSK3" },
  { hanzi: "护照", pinyin: "hùzhào", meaning: "passport", level: "HSK3" },
  { hanzi: "花", pinyin: "huā", meaning: "spend / flower", level: "HSK3" },
  { hanzi: "画", pinyin: "huà", meaning: "draw", level: "HSK3" },
  { hanzi: "坏", pinyin: "huài", meaning: "bad", level: "HSK3" },
  { hanzi: "欢迎", pinyin: "huānyíng", meaning: "welcome", level: "HSK3" },
  { hanzi: "还", pinyin: "huán", meaning: "return", level: "HSK3" },
  { hanzi: "环境", pinyin: "huánjìng", meaning: "environment", level: "HSK3" },
  { hanzi: "换", pinyin: "huàn", meaning: "change", level: "HSK3" },
  { hanzi: "黄河", pinyin: "huánghé", meaning: "Yellow River", level: "HSK3" },
  { hanzi: "回答", pinyin: "huídá", meaning: "answer", level: "HSK3" },
  { hanzi: "会议", pinyin: "huìyì", meaning: "meeting", level: "HSK3" },
  { hanzi: "或者", pinyin: "huòzhě", meaning: "or", level: "HSK3" },
  { hanzi: "几乎", pinyin: "jīhū", meaning: "almost", level: "HSK3" },
  { hanzi: "机会", pinyin: "jīhuì", meaning: "opportunity", level: "HSK3" },
  { hanzi: "极", pinyin: "jí", meaning: "extremely", level: "HSK3" },
  { hanzi: "记得", pinyin: "jìde", meaning: "remember", level: "HSK3" },
  { hanzi: "季节", pinyin: "jìjié", meaning: "season", level: "HSK3" },
  { hanzi: "检查", pinyin: "jiǎnchá", meaning: "check", level: "HSK3" },
  { hanzi: "简单", pinyin: "jiǎndān", meaning: "simple", level: "HSK3" },
  { hanzi: "健康", pinyin: "jiànkāng", meaning: "healthy", level: "HSK3" },
  { hanzi: "见面", pinyin: "jiànmiàn", meaning: "meet", level: "HSK3" },
  { hanzi: "讲", pinyin: "jiǎng", meaning: "speak", level: "HSK3" },
  { hanzi: "教", pinyin: "jiāo", meaning: "teach", level: "HSK3" },
  { hanzi: "角", pinyin: "jiǎo", meaning: "angle", level: "HSK3" },
  { hanzi: "脚", pinyin: "jiǎo", meaning: "foot", level: "HSK3" },
  { hanzi: "接", pinyin: "jiē", meaning: "pick up", level: "HSK3" },
  { hanzi: "街道", pinyin: "jiēdào", meaning: "street", level: "HSK3" },
  { hanzi: "结婚", pinyin: "jiéhūn", meaning: "marry", level: "HSK3" },
  { hanzi: "结束", pinyin: "jiéshù", meaning: "end", level: "HSK3" },
  { hanzi: "节目", pinyin: "jiémù", meaning: "program", level: "HSK3" },
  { hanzi: "节日", pinyin: "jiérì", meaning: "festival", level: "HSK3" },
  { hanzi: "解决", pinyin: "jiějué", meaning: "solve", level: "HSK3" },
  { hanzi: "借", pinyin: "jiè", meaning: "borrow", level: "HSK3" },
  { hanzi: "经常", pinyin: "jīngcháng", meaning: "often", level: "HSK3" },
  { hanzi: "经过", pinyin: "jīngguò", meaning: "pass through", level: "HSK3" },
  { hanzi: "经理", pinyin: "jīnglǐ", meaning: "manager", level: "HSK3" },
  { hanzi: "久", pinyin: "jiǔ", meaning: "long (time)", level: "HSK3" },
  { hanzi: "旧", pinyin: "jiù", meaning: "old", level: "HSK3" },
  { hanzi: "句子", pinyin: "jùzi", meaning: "sentence", level: "HSK3" },
  { hanzi: "决定", pinyin: "juédìng", meaning: "decide", level: "HSK3" },
  { hanzi: "渴", pinyin: "kě", meaning: "thirsty", level: "HSK3" },
  { hanzi: "可爱", pinyin: "kě’ài", meaning: "cute", level: "HSK3" },
  { hanzi: "刻", pinyin: "kè", meaning: "moment", level: "HSK3" },
  { hanzi: "客人", pinyin: "kèrén", meaning: "guest", level: "HSK3" },
  { hanzi: "空调", pinyin: "kōngtiáo", meaning: "air conditioner", level: "HSK3" },
  { hanzi: "口", pinyin: "kǒu", meaning: "mouth", level: "HSK3" },
  { hanzi: "哭", pinyin: "kū", meaning: "cry", level: "HSK3" },
  { hanzi: "裤子", pinyin: "kùzi", meaning: "pants", level: "HSK3" },
  { hanzi: "筷子", pinyin: "kuàizi", meaning: "chopsticks", level: "HSK3" },
  { hanzi: "蓝", pinyin: "lán", meaning: "blue", level: "HSK3" },
  { hanzi: "老", pinyin: "lǎo", meaning: "old", level: "HSK3" },
  { hanzi: "离开", pinyin: "líkāi", meaning: "leave", level: "HSK3" },
  { hanzi: "礼物", pinyin: "lǐwù", meaning: "gift", level: "HSK3" },
  { hanzi: "历史", pinyin: "lìshǐ", meaning: "history", level: "HSK3" },
  { hanzi: "脸", pinyin: "liǎn", meaning: "face", level: "HSK3" },
  { hanzi: "聊天", pinyin: "liáotiān", meaning: "chat", level: "HSK3" },
  { hanzi: "练习", pinyin: "liànxí", meaning: "practice", level: "HSK3" },
  { hanzi: "辆", pinyin: "liàng", meaning: "(measure word for vehicles)", level: "HSK3" },
  { hanzi: "了解", pinyin: "liǎojiě", meaning: "understand", level: "HSK3" },
  { hanzi: "邻居", pinyin: "línjū", meaning: "neighbor", level: "HSK3" },
  { hanzi: "留学", pinyin: "liúxué", meaning: "study abroad", level: "HSK3" },
  { hanzi: "楼", pinyin: "lóu", meaning: "building", level: "HSK3" },
  { hanzi: "绿", pinyin: "lǜ", meaning: "green", level: "HSK3" },
  { hanzi: "马", pinyin: "mǎ", meaning: "horse", level: "HSK3" },
  { hanzi: "马上", pinyin: "mǎshàng", meaning: "immediately", level: "HSK3" },
  { hanzi: "满意", pinyin: "mǎnyì", meaning: "satisfied", level: "HSK3" },
  { hanzi: "帽子", pinyin: "màozi", meaning: "hat", level: "HSK3" },
  { hanzi: "米", pinyin: "mǐ", meaning: "meter / rice", level: "HSK3" },
  { hanzi: "面包", pinyin: "miànbāo", meaning: "bread", level: "HSK3" },
  { hanzi: "明白", pinyin: "míngbai", meaning: "understand clearly", level: "HSK3" },
  { hanzi: "拿", pinyin: "ná", meaning: "take", level: "HSK3" },
  { hanzi: "奶奶", pinyin: "nǎinai", meaning: "grandmother", level: "HSK3" },
  { hanzi: "南", pinyin: "nán", meaning: "south", level: "HSK3" },
  { hanzi: "难", pinyin: "nán", meaning: "difficult", level: "HSK3" },
  { hanzi: "难过", pinyin: "nánguò", meaning: "sad", level: "HSK3" },
  { hanzi: "年级", pinyin: "niánjí", meaning: "grade (school)", level: "HSK3" },
  { hanzi: "年轻", pinyin: "niánqīng", meaning: "young", level: "HSK3" },
  { hanzi: "鸟", pinyin: "niǎo", meaning: "bird", level: "HSK3" },
  { hanzi: "努力", pinyin: "nǔlì", meaning: "work hard", level: "HSK3" },
  { hanzi: "爬山", pinyin: "páshān", meaning: "climb a mountain", level: "HSK3" },
  { hanzi: "盘子", pinyin: "pánzi", meaning: "plate", level: "HSK3" },
  { hanzi: "胖", pinyin: "pàng", meaning: "fat", level: "HSK3" },
  { hanzi: "啤酒", pinyin: "píjiǔ", meaning: "beer", level: "HSK3" },
  { hanzi: "皮鞋", pinyin: "píxié", meaning: "leather shoes", level: "HSK3" },
  { hanzi: "瓶子", pinyin: "píngzi", meaning: "bottle", level: "HSK3" },
  { hanzi: "其实", pinyin: "qíshí", meaning: "actually", level: "HSK3" },
  { hanzi: "其他", pinyin: "qítā", meaning: "other", level: "HSK3" },
  { hanzi: "骑", pinyin: "qí", meaning: "ride", level: "HSK3" },
  { hanzi: "奇怪", pinyin: "qíguài", meaning: "strange", level: "HSK3" },
  { hanzi: "起来", pinyin: "qǐlái", meaning: "rise / get up", level: "HSK3" },
  { hanzi: "起飞", pinyin: "qǐfēi", meaning: "take off", level: "HSK3" },
  { hanzi: "清楚", pinyin: "qīngchu", meaning: "clear", level: "HSK3" },
  { hanzi: "请假", pinyin: "qǐngjià", meaning: "ask for leave", level: "HSK3" },
  { hanzi: "秋", pinyin: "qiū", meaning: "autumn", level: "HSK3" },
  { hanzi: "裙子", pinyin: "qúnzi", meaning: "skirt", level: "HSK3" },
  { hanzi: "然后", pinyin: "ránhòu", meaning: "then", level: "HSK3" },
  { hanzi: "热情", pinyin: "rèqíng", meaning: "enthusiastic", level: "HSK3" },
  { hanzi: "认为", pinyin: "rènwéi", meaning: "think (opinion)", level: "HSK3" },
  { hanzi: "认真", pinyin: "rènzhēn", meaning: "serious", level: "HSK3" },
  { hanzi: "容易", pinyin: "róngyì", meaning: "easy", level: "HSK3" },
  { hanzi: "如果", pinyin: "rúguǒ", meaning: "if", level: "HSK3" },
  { hanzi: "伞", pinyin: "sǎn", meaning: "umbrella", level: "HSK3" },
  { hanzi: "上网", pinyin: "shàngwǎng", meaning: "go online", level: "HSK3" },
  { hanzi: "生气", pinyin: "shēngqì", meaning: "angry", level: "HSK3" },
  { hanzi: "声音", pinyin: "shēngyīn", meaning: "sound", level: "HSK3" },
  { hanzi: "试", pinyin: "shì", meaning: "try", level: "HSK3" },
  { hanzi: "世界", pinyin: "shìjiè", meaning: "world", level: "HSK3" },
  { hanzi: "瘦", pinyin: "shòu", meaning: "thin", level: "HSK3" },
  { hanzi: "舒服", pinyin: "shūfu", meaning: "comfortable", level: "HSK3" },
  { hanzi: "叔叔", pinyin: "shūshu", meaning: "uncle", level: "HSK3" },
  { hanzi: "树", pinyin: "shù", meaning: "tree", level: "HSK3" },
  { hanzi: "数学", pinyin: "shùxué", meaning: "math", level: "HSK3" },
  { hanzi: "刷牙", pinyin: "shuāyá", meaning: "brush teeth", level: "HSK3" },
  { hanzi: "双", pinyin: "shuāng", meaning: "pair", level: "HSK3" },
  { hanzi: "水平", pinyin: "shuǐpíng", meaning: "level", level: "HSK3" },
  { hanzi: "司机", pinyin: "sījī", meaning: "driver", level: "HSK3" },
  { hanzi: "太阳", pinyin: "tàiyáng", meaning: "sun", level: "HSK3" },
  { hanzi: "特别", pinyin: "tèbié", meaning: "especially", level: "HSK3" },
  { hanzi: "疼", pinyin: "téng", meaning: "hurt", level: "HSK3" },
  { hanzi: "提高", pinyin: "tígāo", meaning: "improve", level: "HSK3" },
  { hanzi: "体育", pinyin: "tǐyù", meaning: "sports", level: "HSK3" },
  { hanzi: "甜", pinyin: "tián", meaning: "sweet", level: "HSK3" },
  { hanzi: "条", pinyin: "tiáo", meaning: "(measure word)", level: "HSK3" },
  { hanzi: "同事", pinyin: "tóngshì", meaning: "colleague", level: "HSK3" },
  { hanzi: "同意", pinyin: "tóngyì", meaning: "agree", level: "HSK3" },
  { hanzi: "头发", pinyin: "tóufa", meaning: "hair", level: "HSK3" },
  { hanzi: "突然", pinyin: "tūrán", meaning: "suddenly", level: "HSK3" },
  { hanzi: "图书馆", pinyin: "túshūguǎn", meaning: "library", level: "HSK3" },
  { hanzi: "腿", pinyin: "tuǐ", meaning: "leg", level: "HSK3" },
  { hanzi: "完成", pinyin: "wánchéng", meaning: "complete", level: "HSK3" },
  { hanzi: "碗", pinyin: "wǎn", meaning: "bowl", level: "HSK3" },
  { hanzi: "万", pinyin: "wàn", meaning: "ten thousand", level: "HSK3" },
  { hanzi: "忘记", pinyin: "wàngjì", meaning: "forget", level: "HSK3" },
  { hanzi: "为", pinyin: "wèi", meaning: "for", level: "HSK3" },
  { hanzi: "为了", pinyin: "wèile", meaning: "in order to", level: "HSK3" },
  { hanzi: "位", pinyin: "wèi", meaning: "(measure word for people)", level: "HSK3" },
  { hanzi: "文化", pinyin: "wénhuà", meaning: "culture", level: "HSK3" },
  { hanzi: "西", pinyin: "xī", meaning: "west", level: "HSK3" },
  { hanzi: "习惯", pinyin: "xíguàn", meaning: "habit", level: "HSK3" },
  { hanzi: "洗手间", pinyin: "xǐshǒujiān", meaning: "restroom", level: "HSK3" },
  { hanzi: "洗澡", pinyin: "xǐzǎo", meaning: "shower", level: "HSK3" },
  { hanzi: "夏", pinyin: "xià", meaning: "summer", level: "HSK3" },
  { hanzi: "先", pinyin: "xiān", meaning: "first", level: "HSK3" },
  { hanzi: "香蕉", pinyin: "xiāngjiāo", meaning: "banana", level: "HSK3" },
  { hanzi: "相信", pinyin: "xiāngxìn", meaning: "believe", level: "HSK3" },
  { hanzi: "向", pinyin: "xiàng", meaning: "toward", level: "HSK3" },
  { hanzi: "像", pinyin: "xiàng", meaning: "like / resemble", level: "HSK3" },
  { hanzi: "小心", pinyin: "xiǎoxīn", meaning: "be careful", level: "HSK3" },
  { hanzi: "校长", pinyin: "xiàozhǎng", meaning: "principal", level: "HSK3" },
  { hanzi: "新闻", pinyin: "xīnwén", meaning: "news", level: "HSK3" },
  { hanzi: "新鲜", pinyin: "xīnxiān", meaning: "fresh", level: "HSK3" },
  { hanzi: "信用卡", pinyin: "xìnyòngkǎ", meaning: "credit card", level: "HSK3" },
  { hanzi: "行李箱", pinyin: "xínglixiāng", meaning: "suitcase", level: "HSK3" },
  { hanzi: "熊猫", pinyin: "xióngmāo", meaning: "panda", level: "HSK3" },
  { hanzi: "需要", pinyin: "xūyào", meaning: "need", level: "HSK3" },
  { hanzi: "选择", pinyin: "xuǎnzé", meaning: "choose", level: "HSK3" },
  { hanzi: "要求", pinyin: "yāoqiú", meaning: "require", level: "HSK3" },
  { hanzi: "爷爷", pinyin: "yéye", meaning: "grandfather", level: "HSK3" },
  { hanzi: "一定", pinyin: "yídìng", meaning: "definitely", level: "HSK3" },
  { hanzi: "一共", pinyin: "yígòng", meaning: "in total", level: "HSK3" },
  { hanzi: "一会儿", pinyin: "yíhuìr", meaning: "a while", level: "HSK3" },
  { hanzi: "一样", pinyin: "yíyàng", meaning: "same", level: "HSK3" },
  { hanzi: "以前", pinyin: "yǐqián", meaning: "before", level: "HSK3" },
  { hanzi: "一般", pinyin: "yìbān", meaning: "generally", level: "HSK3" },
  { hanzi: "一边", pinyin: "yìbiān", meaning: "one side / while", level: "HSK3" },
  { hanzi: "一直", pinyin: "yìzhí", meaning: "always", level: "HSK3" },
  { hanzi: "音乐", pinyin: "yīnyuè", meaning: "music", level: "HSK3" },
  { hanzi: "银行", pinyin: "yínháng", meaning: "bank", level: "HSK3" },
  { hanzi: "饮料", pinyin: "yǐnliào", meaning: "drink", level: "HSK3" },
  { hanzi: "应该", pinyin: "yīnggāi", meaning: "should", level: "HSK3" },
  { hanzi: "影响", pinyin: "yǐngxiǎng", meaning: "influence", level: "HSK3" },
  { hanzi: "用", pinyin: "yòng", meaning: "use", level: "HSK3" },
  { hanzi: "游戏", pinyin: "yóuxì", meaning: "game", level: "HSK3" },
  { hanzi: "有名", pinyin: "yǒumíng", meaning: "famous", level: "HSK3" },
  { hanzi: "又", pinyin: "yòu", meaning: "again", level: "HSK3" },
  { hanzi: "遇到", pinyin: "yùdào", meaning: "meet", level: "HSK3" },
  { hanzi: "元", pinyin: "yuán", meaning: "yuan", level: "HSK3" },
  { hanzi: "愿意", pinyin: "yuànyì", meaning: "willing", level: "HSK3" },
  { hanzi: "月亮", pinyin: "yuèliang", meaning: "moon", level: "HSK3" },
  { hanzi: "越", pinyin: "yuè", meaning: "more and more", level: "HSK3" },
  { hanzi: "站", pinyin: "zhàn", meaning: "station", level: "HSK3" },
  { hanzi: "张", pinyin: "zhāng", meaning: "(measure word)", level: "HSK3" },
  { hanzi: "长", pinyin: "zhǎng", meaning: "grow", level: "HSK3" },
  { hanzi: "着急", pinyin: "zháojí", meaning: "anxious", level: "HSK3" },
  { hanzi: "照顾", pinyin: "zhàogù", meaning: "take care", level: "HSK3" },
  { hanzi: "照片", pinyin: "zhàopiàn", meaning: "photo", level: "HSK3" },
  { hanzi: "照相机", pinyin: "zhàoxiàngjī", meaning: "camera", level: "HSK3" },
  { hanzi: "只", pinyin: "zhī", meaning: "(measure word)", level: "HSK3" },
  { hanzi: "只", pinyin: "zhǐ", meaning: "only", level: "HSK3" },
  { hanzi: "只有……才……", pinyin: "zhǐyǒu…cái…", meaning: "only if...then...", level: "HSK3" },
  { hanzi: "中文", pinyin: "zhōngwén", meaning: "Chinese", level: "HSK3" },
  { hanzi: "中间", pinyin: "zhōngjiān", meaning: "middle", level: "HSK3" },
  { hanzi: "终于", pinyin: "zhōngyú", meaning: "finally", level: "HSK3" },
  { hanzi: "种", pinyin: "zhǒng", meaning: "type", level: "HSK3" },
  { hanzi: "重要", pinyin: "zhòngyào", meaning: "important", level: "HSK3" },
  { hanzi: "周末", pinyin: "zhōumò", meaning: "weekend", level: "HSK3" },
  { hanzi: "主要", pinyin: "zhǔyào", meaning: "main", level: "HSK3" },
  { hanzi: "注意", pinyin: "zhùyì", meaning: "pay attention", level: "HSK3" },
  { hanzi: "自己", pinyin: "zìjǐ", meaning: "self", level: "HSK3" },
  { hanzi: "自行车", pinyin: "zìxíngchē", meaning: "bicycle", level: "HSK3" },
  { hanzi: "总是", pinyin: "zǒngshì", meaning: "always", level: "HSK3" },
  { hanzi: "嘴", pinyin: "zuǐ", meaning: "mouth", level: "HSK3" },
  { hanzi: "最后", pinyin: "zuìhòu", meaning: "last", level: "HSK3" },
  { hanzi: "最近", pinyin: "zuìjìn", meaning: "recently", level: "HSK3" },
  { hanzi: "作业", pinyin: "zuòyè", meaning: "homework", level: "HSK3" },

  // HSK 4
  { hanzi: "爱情", pinyin: "àiqíng", meaning: "love", level: "HSK4" },
  { hanzi: "安排", pinyin: "ānpái", meaning: "arrange", level: "HSK4" },
  { hanzi: "安全", pinyin: "ānquán", meaning: "safety", level: "HSK4" },
  { hanzi: "按时", pinyin: "ànshí", meaning: "on time", level: "HSK4" },
  { hanzi: "按照", pinyin: "ànzhào", meaning: "according to", level: "HSK4" },
  { hanzi: "百分之", pinyin: "bǎifēnzhī", meaning: "percent", level: "HSK4" },
  { hanzi: "棒", pinyin: "bàng", meaning: "excellent", level: "HSK4" },
  { hanzi: "包子", pinyin: "bāozi", meaning: "steamed bun", level: "HSK4" },
  { hanzi: "保护", pinyin: "bǎohù", meaning: "protect", level: "HSK4" },
  { hanzi: "保证", pinyin: "bǎozhèng", meaning: "guarantee", level: "HSK4" },
  { hanzi: "抱", pinyin: "bào", meaning: "hold", level: "HSK4" },
  { hanzi: "抱歉", pinyin: "bàoqiàn", meaning: "sorry", level: "HSK4" },
  { hanzi: "报名", pinyin: "bàomíng", meaning: "sign up", level: "HSK4" },
  { hanzi: "倍", pinyin: "bèi", meaning: "times (multiple)", level: "HSK4" },
  { hanzi: "本来", pinyin: "běnlái", meaning: "originally", level: "HSK4" },
  { hanzi: "笨", pinyin: "bèn", meaning: "stupid", level: "HSK4" },
  { hanzi: "比如", pinyin: "bǐrú", meaning: "for example", level: "HSK4" },
  { hanzi: "毕业", pinyin: "bìyè", meaning: "graduate", level: "HSK4" },
  { hanzi: "遍", pinyin: "biàn", meaning: "times (for actions)", level: "HSK4" },
  { hanzi: "标准", pinyin: "biāozhǔn", meaning: "standard", level: "HSK4" },
  { hanzi: "表格", pinyin: "biǎogé", meaning: "form", level: "HSK4" },
  { hanzi: "表示", pinyin: "biǎoshì", meaning: "express", level: "HSK4" },
  { hanzi: "表演", pinyin: "biǎoyǎn", meaning: "perform", level: "HSK4" },
  { hanzi: "表扬", pinyin: "biǎoyáng", meaning: "praise", level: "HSK4" },
  { hanzi: "饼干", pinyin: "bǐnggān", meaning: "biscuit", level: "HSK4" },
  { hanzi: "并且", pinyin: "bìngqiě", meaning: "and also", level: "HSK4" },
  { hanzi: "博士", pinyin: "bóshì", meaning: "PhD", level: "HSK4" },
  { hanzi: "不过", pinyin: "búguò", meaning: "however", level: "HSK4" },
  { hanzi: "不得不", pinyin: "bùdébù", meaning: "have to", level: "HSK4" },
  { hanzi: "不管", pinyin: "bùguǎn", meaning: "no matter", level: "HSK4" },
  { hanzi: "不仅", pinyin: "bùjǐn", meaning: "not only", level: "HSK4" },
  { hanzi: "部分", pinyin: "bùfen", meaning: "part", level: "HSK4" },
  { hanzi: "擦", pinyin: "cā", meaning: "wipe", level: "HSK4" },
  { hanzi: "猜", pinyin: "cāi", meaning: "guess", level: "HSK4" },
  { hanzi: "材料", pinyin: "cáiliào", meaning: "material", level: "HSK4" },
  { hanzi: "参观", pinyin: "cānguān", meaning: "visit", level: "HSK4" },
  { hanzi: "餐厅", pinyin: "cāntīng", meaning: "restaurant", level: "HSK4" },
  { hanzi: "差不多", pinyin: "chàbuduō", meaning: "almost", level: "HSK4" },
  { hanzi: "尝", pinyin: "cháng", meaning: "taste", level: "HSK4" },
  { hanzi: "长城", pinyin: "chángchéng", meaning: "Great Wall", level: "HSK4" },
  { hanzi: "长江", pinyin: "chángjiāng", meaning: "Yangtze River", level: "HSK4" },
  { hanzi: "场", pinyin: "chǎng", meaning: "place / measure word", level: "HSK4" },
  { hanzi: "超过", pinyin: "chāoguò", meaning: "exceed", level: "HSK4" },
  { hanzi: "厕所", pinyin: "cèsuǒ", meaning: "toilet", level: "HSK4" },
  { hanzi: "成功", pinyin: "chénggōng", meaning: "success", level: "HSK4" },
  { hanzi: "成为", pinyin: "chéngwéi", meaning: "become", level: "HSK4" },
  { hanzi: "诚实", pinyin: "chéngshí", meaning: "honest", level: "HSK4" },
  { hanzi: "乘坐", pinyin: "chéngzuò", meaning: "ride (transport)", level: "HSK4" },
  { hanzi: "吃惊", pinyin: "chījīng", meaning: "be surprised", level: "HSK4" },
  { hanzi: "重新", pinyin: "chóngxīn", meaning: "again", level: "HSK4" },
  { hanzi: "抽烟", pinyin: "chōuyān", meaning: "smoke", level: "HSK4" },
  { hanzi: "出差", pinyin: "chūchāi", meaning: "business trip", level: "HSK4" },
  { hanzi: "出发", pinyin: "chūfā", meaning: "set off", level: "HSK4" },
  { hanzi: "出生", pinyin: "chūshēng", meaning: "be born", level: "HSK4" },
  { hanzi: "出现", pinyin: "chūxiàn", meaning: "appear", level: "HSK4" },
  { hanzi: "厨房", pinyin: "chúfáng", meaning: "kitchen", level: "HSK4" },
  { hanzi: "传真", pinyin: "chuánzhēn", meaning: "fax", level: "HSK4" },
  { hanzi: "窗户", pinyin: "chuānghu", meaning: "window", level: "HSK4" },
  { hanzi: "词语", pinyin: "cíyǔ", meaning: "word", level: "HSK4" },
  { hanzi: "从来", pinyin: "cónglái", meaning: "always", level: "HSK4" },
  { hanzi: "粗心", pinyin: "cūxīn", meaning: "careless", level: "HSK4" },
  { hanzi: "存", pinyin: "cún", meaning: "save/store", level: "HSK4" },
  { hanzi: "错误", pinyin: "cuòwù", meaning: "mistake", level: "HSK4" },
  { hanzi: "答案", pinyin: "dá’àn", meaning: "answer", level: "HSK4" },
  { hanzi: "打招呼", pinyin: "dǎzhāohu", meaning: "greet", level: "HSK4" },
  { hanzi: "打扮", pinyin: "dǎban", meaning: "dress up", level: "HSK4" },
  { hanzi: "打扰", pinyin: "dǎrǎo", meaning: "disturb", level: "HSK4" },
  { hanzi: "打印", pinyin: "dǎyìn", meaning: "print", level: "HSK4" },
  { hanzi: "打折", pinyin: "dǎzhé", meaning: "discount", level: "HSK4" },
  { hanzi: "打针", pinyin: "dǎzhēn", meaning: "injection", level: "HSK4" },
  { hanzi: "大概", pinyin: "dàgài", meaning: "probably", level: "HSK4" },
  { hanzi: "大使馆", pinyin: "dàshǐguǎn", meaning: "embassy", level: "HSK4" },
  { hanzi: "大约", pinyin: "dàyuē", meaning: "about", level: "HSK4" },
  { hanzi: "戴", pinyin: "dài", meaning: "wear (accessories)", level: "HSK4" },
  { hanzi: "大夫", pinyin: "dàifu", meaning: "doctor", level: "HSK4" },
  { hanzi: "当", pinyin: "dāng", meaning: "when", level: "HSK4" },
  { hanzi: "当时", pinyin: "dāngshí", meaning: "at that time", level: "HSK4" },
  { hanzi: "刀", pinyin: "dāo", meaning: "knife", level: "HSK4" },
  { hanzi: "导游", pinyin: "dǎoyóu", meaning: "tour guide", level: "HSK4" },
  { hanzi: "倒", pinyin: "dào", meaning: "pour / upside down", level: "HSK4" },
  { hanzi: "假", pinyin: "jiǎ", meaning: "fake / false", level: "HSK4" },
  { hanzi: "价格", pinyin: "jiàgé", meaning: "price", level: "HSK4" },
  { hanzi: "坚持", pinyin: "jiānchí", meaning: "insist", level: "HSK4" },
  { hanzi: "减肥", pinyin: "jiǎnféi", meaning: "lose weight", level: "HSK4" },
  { hanzi: "减少", pinyin: "jiǎnshǎo", meaning: "reduce", level: "HSK4" },
  { hanzi: "建议", pinyin: "jiànyì", meaning: "suggestion", level: "HSK4" },
  { hanzi: "将来", pinyin: "jiānglái", meaning: "future", level: "HSK4" },
  { hanzi: "奖金", pinyin: "jiǎngjīn", meaning: "bonus", level: "HSK4" },
  { hanzi: "降低", pinyin: "jiàngdī", meaning: "lower", level: "HSK4" },
  { hanzi: "降落", pinyin: "jiàngluò", meaning: "land", level: "HSK4" },
  { hanzi: "交", pinyin: "jiāo", meaning: "hand over", level: "HSK4" },
  { hanzi: "交流", pinyin: "jiāoliú", meaning: "communicate", level: "HSK4" },
  { hanzi: "交通", pinyin: "jiāotōng", meaning: "traffic", level: "HSK4" },
  { hanzi: "郊区", pinyin: "jiāoqū", meaning: "suburb", level: "HSK4" },
  { hanzi: "骄傲", pinyin: "jiāo’ào", meaning: "proud", level: "HSK4" },
  { hanzi: "饺子", pinyin: "jiǎozi", meaning: "dumpling", level: "HSK4" },
  { hanzi: "教授", pinyin: "jiàoshòu", meaning: "professor", level: "HSK4" },
  { hanzi: "教育", pinyin: "jiàoyù", meaning: "education", level: "HSK4" },
  { hanzi: "接受", pinyin: "jiēshòu", meaning: "accept", level: "HSK4" },
  { hanzi: "接着", pinyin: "jiēzhe", meaning: "then", level: "HSK4" },
  { hanzi: "结果", pinyin: "jiéguǒ", meaning: "result", level: "HSK4" },
  { hanzi: "节", pinyin: "jié", meaning: "festival / section", level: "HSK4" },
  { hanzi: "节约", pinyin: "jiéyuē", meaning: "save", level: "HSK4" },
  { hanzi: "解释", pinyin: "jiěshì", meaning: "explain", level: "HSK4" },
  { hanzi: "尽管", pinyin: "jǐnguǎn", meaning: "although", level: "HSK4" },
  { hanzi: "紧张", pinyin: "jǐnzhāng", meaning: "nervous", level: "HSK4" },
  { hanzi: "进行", pinyin: "jìnxíng", meaning: "carry out", level: "HSK4" },
  { hanzi: "禁止", pinyin: "jìnzhǐ", meaning: "forbid", level: "HSK4" },
  { hanzi: "精彩", pinyin: "jīngcǎi", meaning: "wonderful", level: "HSK4" },
  { hanzi: "经济", pinyin: "jīngjì", meaning: "economy", level: "HSK4" },
  { hanzi: "经历", pinyin: "jīnglì", meaning: "experience", level: "HSK4" },
  { hanzi: "经验", pinyin: "jīngyàn", meaning: "experience (knowledge)", level: "HSK4" },
  { hanzi: "京剧", pinyin: "jīngjù", meaning: "Beijing opera", level: "HSK4" },
  { hanzi: "警察", pinyin: "jǐngchá", meaning: "police", level: "HSK4" },
  { hanzi: "景色", pinyin: "jǐngsè", meaning: "scenery", level: "HSK4" },
  { hanzi: "竟然", pinyin: "jìngrán", meaning: "unexpectedly", level: "HSK4" },
  { hanzi: "竞争", pinyin: "jìngzhēng", meaning: "compete", level: "HSK4" },
  { hanzi: "镜子", pinyin: "jìngzi", meaning: "mirror", level: "HSK4" },
  { hanzi: "究竟", pinyin: "jiūjìng", meaning: "exactly", level: "HSK4" },
  { hanzi: "举", pinyin: "jǔ", meaning: "lift", level: "HSK4" },
  { hanzi: "举办", pinyin: "jǔbàn", meaning: "hold (event)", level: "HSK4" },
  { hanzi: "举行", pinyin: "jǔxíng", meaning: "hold", level: "HSK4" },
  { hanzi: "拒绝", pinyin: "jùjué", meaning: "refuse", level: "HSK4" },
  { hanzi: "距离", pinyin: "jùlí", meaning: "distance", level: "HSK4" },
  { hanzi: "聚会", pinyin: "jùhuì", meaning: "party", level: "HSK4" },
  { hanzi: "开玩笑", pinyin: "kāiwánxiào", meaning: "joke", level: "HSK4" },
  { hanzi: "开心", pinyin: "kāixīn", meaning: "happy", level: "HSK4" },
  { hanzi: "看法", pinyin: "kànfǎ", meaning: "opinion", level: "HSK4" },
  { hanzi: "考虑", pinyin: "kǎolǜ", meaning: "consider", level: "HSK4" },
  { hanzi: "烤鸭", pinyin: "kǎoyā", meaning: "roast duck", level: "HSK4" },
  { hanzi: "棵", pinyin: "kē", meaning: "(measure word for trees)", level: "HSK4" },
  { hanzi: "科学", pinyin: "kēxué", meaning: "science", level: "HSK4" },
  { hanzi: "咳嗽", pinyin: "késou", meaning: "cough", level: "HSK4" },
  { hanzi: "可怜", pinyin: "kělián", meaning: "pitiful", level: "HSK4" },
  { hanzi: "可是", pinyin: "kěshì", meaning: "but", level: "HSK4" },
  { hanzi: "可惜", pinyin: "kěxī", meaning: "unfortunately", level: "HSK4" },
  { hanzi: "客厅", pinyin: "kètīng", meaning: "living room", level: "HSK4" },
  { hanzi: "肯定", pinyin: "kěndìng", meaning: "certain", level: "HSK4" },
  { hanzi: "空", pinyin: "kōng", meaning: "empty", level: "HSK4" },
  { hanzi: "空气", pinyin: "kōngqì", meaning: "air", level: "HSK4" },
  { hanzi: "恐怕", pinyin: "kǒngpà", meaning: "probably", level: "HSK4" },
  { hanzi: "苦", pinyin: "kǔ", meaning: "bitter", level: "HSK4" },
  { hanzi: "矿泉水", pinyin: "kuàngquánshuǐ", meaning: "mineral water", level: "HSK4" },
  { hanzi: "困", pinyin: "kùn", meaning: "sleepy", level: "HSK4" },
  { hanzi: "困难", pinyin: "kùnnan", meaning: "difficulty", level: "HSK4" },
  { hanzi: "拉", pinyin: "lā", meaning: "pull", level: "HSK4" },
  { hanzi: "垃圾桶", pinyin: "lājītǒng", meaning: "trash can", level: "HSK4" },
  { hanzi: "辣", pinyin: "là", meaning: "spicy", level: "HSK4" },
  { hanzi: "来自", pinyin: "láizì", meaning: "come from", level: "HSK4" },
  { hanzi: "来不及", pinyin: "láibují", meaning: "too late", level: "HSK4" },
  { hanzi: "来得及", pinyin: "láidejí", meaning: "in time", level: "HSK4" },
  { hanzi: "懒", pinyin: "lǎn", meaning: "lazy", level: "HSK4" },
  { hanzi: "浪费", pinyin: "làngfèi", meaning: "waste", level: "HSK4" },
  { hanzi: "浪漫", pinyin: "làngmàn", meaning: "romantic", level: "HSK4" },
  { hanzi: "老虎", pinyin: "lǎohǔ", meaning: "tiger", level: "HSK4" },
  { hanzi: "冷静", pinyin: "lěngjìng", meaning: "calm", level: "HSK4" },
  { hanzi: "理发", pinyin: "lǐfà", meaning: "haircut", level: "HSK4" },
  { hanzi: "理解", pinyin: "lǐjiě", meaning: "understand", level: "HSK4" },
  { hanzi: "理想", pinyin: "lǐxiǎng", meaning: "ideal", level: "HSK4" },
  { hanzi: "礼貌", pinyin: "lǐmào", meaning: "polite", level: "HSK4" },
  { hanzi: "礼拜天", pinyin: "lǐbàitiān", meaning: "Sunday", level: "HSK4" },
  { hanzi: "厉害", pinyin: "lìhai", meaning: "awesome / serious", level: "HSK4" },
  { hanzi: "力气", pinyin: "lìqi", meaning: "strength", level: "HSK4" },
  { hanzi: "例如", pinyin: "lìrú", meaning: "for example", level: "HSK4" },
  { hanzi: "俩", pinyin: "liǎ", meaning: "two (spoken)", level: "HSK4" },
  { hanzi: "连", pinyin: "lián", meaning: "even", level: "HSK4" },
  { hanzi: "联系", pinyin: "liánxì", meaning: "contact", level: "HSK4" },
  { hanzi: "凉快", pinyin: "liángkuai", meaning: "cool", level: "HSK4" },
  { hanzi: "零钱", pinyin: "língqián", meaning: "change (money)", level: "HSK4" },
  { hanzi: "另外", pinyin: "lìngwài", meaning: "in addition", level: "HSK4" },
  { hanzi: "留", pinyin: "liú", meaning: "stay", level: "HSK4" },
  { hanzi: "流利", pinyin: "liúlì", meaning: "fluent", level: "HSK4" },
  { hanzi: "流行", pinyin: "liúxíng", meaning: "popular", level: "HSK4" },
  { hanzi: "乱", pinyin: "luàn", meaning: "messy", level: "HSK4" },
  { hanzi: "旅行", pinyin: "lǚxíng", meaning: "travel", level: "HSK4" },
  { hanzi: "律师", pinyin: "lǜshī", meaning: "lawyer", level: "HSK4" },
  { hanzi: "麻烦", pinyin: "máfan", meaning: "trouble", level: "HSK4" },
  { hanzi: "马虎", pinyin: "mǎhu", meaning: "careless", level: "HSK4" },
  { hanzi: "满", pinyin: "mǎn", meaning: "full", level: "HSK4" },
  { hanzi: "毛", pinyin: "máo", meaning: "hair", level: "HSK4" },
  { hanzi: "毛巾", pinyin: "máojīn", meaning: "towel", level: "HSK4" },
  { hanzi: "美丽", pinyin: "měilì", meaning: "beautiful", level: "HSK4" },
  { hanzi: "梦", pinyin: "mèng", meaning: "dream", level: "HSK4" },
  { hanzi: "迷路", pinyin: "mílù", meaning: "get lost", level: "HSK4" },
  { hanzi: "密码", pinyin: "mìmǎ", meaning: "password", level: "HSK4" },
  { hanzi: "免费", pinyin: "miǎnfèi", meaning: "free of charge", level: "HSK4" },
  { hanzi: "秒", pinyin: "miǎo", meaning: "second (time)", level: "HSK4" },
  { hanzi: "民族", pinyin: "mínzú", meaning: "nation / ethnicity", level: "HSK4" },
  { hanzi: "母亲", pinyin: "mǔqīn", meaning: "mother", level: "HSK4" },
  { hanzi: "目的", pinyin: "mùdì", meaning: "purpose", level: "HSK4" },
  { hanzi: "耐心", pinyin: "nàixīn", meaning: "patience", level: "HSK4" },
  { hanzi: "难道", pinyin: "nándào", meaning: "could it be that...", level: "HSK4" },
  { hanzi: "难受", pinyin: "nánshòu", meaning: "uncomfortable", level: "HSK4" },
  { hanzi: "内", pinyin: "nèi", meaning: "inside", level: "HSK4" },
  { hanzi: "内容", pinyin: "nèiróng", meaning: "content", level: "HSK4" },
  { hanzi: "能力", pinyin: "nénglì", meaning: "ability", level: "HSK4" },
  { hanzi: "年龄", pinyin: "niánlíng", meaning: "age", level: "HSK4" },
  { hanzi: "弄", pinyin: "nòng", meaning: "do / make", level: "HSK4" },
  { hanzi: "暖和", pinyin: "nuǎnhuo", meaning: "warm", level: "HSK4" },
  { hanzi: "偶尔", pinyin: "ǒu’ěr", meaning: "occasionally", level: "HSK4" },
  { hanzi: "排队", pinyin: "páiduì", meaning: "line up", level: "HSK4" },
  { hanzi: "排列", pinyin: "páiliè", meaning: "arrange", level: "HSK4" },
  { hanzi: "判断", pinyin: "pànduàn", meaning: "judge", level: "HSK4" },
  { hanzi: "陪", pinyin: "péi", meaning: "accompany", level: "HSK4" },
  { hanzi: "批评", pinyin: "pīpíng", meaning: "criticize", level: "HSK4" },
  { hanzi: "皮肤", pinyin: "pífū", meaning: "skin", level: "HSK4" },
  { hanzi: "脾气", pinyin: "píqi", meaning: "temper", level: "HSK4" },
  { hanzi: "篇", pinyin: "piān", meaning: "(measure word for articles)", level: "HSK4" },
  { hanzi: "骗", pinyin: "piàn", meaning: "cheat", level: "HSK4" },
  { hanzi: "乒乓球", pinyin: "pīngpāngqiú", meaning: "table tennis", level: "HSK4" },
  { hanzi: "平时", pinyin: "píngshí", meaning: "usually", level: "HSK4" },
  { hanzi: "破", pinyin: "pò", meaning: "broken", level: "HSK4" },
  { hanzi: "葡萄", pinyin: "pútao", meaning: "grape", level: "HSK4" },
  { hanzi: "普遍", pinyin: "pǔbiàn", meaning: "common", level: "HSK4" },
  { hanzi: "普通话", pinyin: "pǔtōnghuà", meaning: "Mandarin", level: "HSK4" },
  { hanzi: "其次", pinyin: "qícì", meaning: "secondly", level: "HSK4" },
  { hanzi: "其中", pinyin: "qízhōng", meaning: "among", level: "HSK4" },
  { hanzi: "气候", pinyin: "qìhòu", meaning: "climate", level: "HSK4" },
  { hanzi: "千万", pinyin: "qiānwàn", meaning: "must / be sure to", level: "HSK4" },
  { hanzi: "签证", pinyin: "qiānzhèng", meaning: "visa", level: "HSK4" },
  { hanzi: "敲", pinyin: "qiāo", meaning: "knock", level: "HSK4" },
  { hanzi: "桥", pinyin: "qiáo", meaning: "bridge", level: "HSK4" },
  { hanzi: "巧克力", pinyin: "qiǎokèlì", meaning: "chocolate", level: "HSK4" },
  { hanzi: "亲戚", pinyin: "qīnqi", meaning: "relative", level: "HSK4" },
  { hanzi: "轻", pinyin: "qīng", meaning: "light", level: "HSK4" },
  { hanzi: "轻松", pinyin: "qīngsōng", meaning: "relaxed", level: "HSK4" },
  { hanzi: "情况", pinyin: "qíngkuàng", meaning: "situation", level: "HSK4" },
  { hanzi: "穷", pinyin: "qióng", meaning: "poor", level: "HSK4" },
  { hanzi: "区别", pinyin: "qūbié", meaning: "difference", level: "HSK4" },
  { hanzi: "取", pinyin: "qǔ", meaning: "take", level: "HSK4" },
  { hanzi: "全部", pinyin: "quánbù", meaning: "all", level: "HSK4" },
  { hanzi: "缺点", pinyin: "quēdiǎn", meaning: "shortcoming", level: "HSK4" },
  { hanzi: "缺少", pinyin: "quēshǎo", meaning: "lack", level: "HSK4" },
  { hanzi: "却", pinyin: "què", meaning: "but", level: "HSK4" },
  { hanzi: "确实", pinyin: "quèshí", meaning: "indeed", level: "HSK4" },
  { hanzi: "然而", pinyin: "rán’ér", meaning: "however", level: "HSK4" },
  { hanzi: "热闹", pinyin: "rènao", meaning: "lively", level: "HSK4" },
  { hanzi: "任何", pinyin: "rènhé", meaning: "any", level: "HSK4" },
  { hanzi: "任务", pinyin: "rènwu", meaning: "task", level: "HSK4" },
  { hanzi: "扔", pinyin: "rēng", meaning: "throw", level: "HSK4" },
  { hanzi: "仍然", pinyin: "réngrán", meaning: "still", level: "HSK4" },
  { hanzi: "日记", pinyin: "rìjì", meaning: "diary", level: "HSK4" },
  { hanzi: "入口", pinyin: "rùkǒu", meaning: "entrance", level: "HSK4" },
  { hanzi: "散步", pinyin: "sànbù", meaning: "take a walk", level: "HSK4" },
  { hanzi: "森林", pinyin: "sēnlín", meaning: "forest", level: "HSK4" },
  { hanzi: "沙发", pinyin: "shāfā", meaning: "sofa", level: "HSK4" },
  { hanzi: "商量", pinyin: "shāngliang", meaning: "discuss", level: "HSK4" },
  { hanzi: "伤心", pinyin: "shāngxīn", meaning: "sad", level: "HSK4" },
  { hanzi: "稍微", pinyin: "shāowēi", meaning: "a little", level: "HSK4" },
  { hanzi: "勺子", pinyin: "sháozi", meaning: "spoon", level: "HSK4" },
  { hanzi: "社会", pinyin: "shèhuì", meaning: "society", level: "HSK4" },
  { hanzi: "深", pinyin: "shēn", meaning: "deep", level: "HSK4" },
  { hanzi: "申请", pinyin: "shēnqǐng", meaning: "apply", level: "HSK4" },
  { hanzi: "甚至", pinyin: "shènzhì", meaning: "even", level: "HSK4" },
  { hanzi: "生活", pinyin: "shēnghuó", meaning: "life", level: "HSK4" },
  { hanzi: "生命", pinyin: "shēngmìng", meaning: "life (biological)", level: "HSK4" },
  { hanzi: "生意", pinyin: "shēngyi", meaning: "business", level: "HSK4" },
  { hanzi: "省", pinyin: "shěng", meaning: "province", level: "HSK4" },
  { hanzi: "剩", pinyin: "shèng", meaning: "remain", level: "HSK4" },
  { hanzi: "失败", pinyin: "shībài", meaning: "fail", level: "HSK4" },
  { hanzi: "失望", pinyin: "shīwàng", meaning: "disappointed", level: "HSK4" },
  { hanzi: "师傅", pinyin: "shīfu", meaning: "master / skilled worker", level: "HSK4" },
  { hanzi: "十分", pinyin: "shífēn", meaning: "very", level: "HSK4" },
  { hanzi: "实际", pinyin: "shíjì", meaning: "actual", level: "HSK4" },
  { hanzi: "实在", pinyin: "shízài", meaning: "really", level: "HSK4" },
  { hanzi: "使", pinyin: "shǐ", meaning: "make / cause", level: "HSK4" },
  { hanzi: "使用", pinyin: "shǐyòng", meaning: "use", level: "HSK4" },
  { hanzi: "是否", pinyin: "shìfǒu", meaning: "whether", level: "HSK4" },
  { hanzi: "适合", pinyin: "shìhé", meaning: "suitable", level: "HSK4" },
  { hanzi: "适应", pinyin: "shìyìng", meaning: "adapt", level: "HSK4" },
  { hanzi: "世纪", pinyin: "shìjì", meaning: "century", level: "HSK4" },
  { hanzi: "收", pinyin: "shōu", meaning: "receive", level: "HSK4" },
  { hanzi: "收入", pinyin: "shōurù", meaning: "income", level: "HSK4" },
  { hanzi: "收拾", pinyin: "shōushi", meaning: "tidy up", level: "HSK4" },
  { hanzi: "首都", pinyin: "shǒudū", meaning: "capital city", level: "HSK4" },
  { hanzi: "首先", pinyin: "shǒuxiān", meaning: "first of all", level: "HSK4" },
  { hanzi: "受不了", pinyin: "shòubuliǎo", meaning: "can't stand", level: "HSK4" },
  { hanzi: "受到", pinyin: "shòudào", meaning: "receive (influence)", level: "HSK4" },
  { hanzi: "售货员", pinyin: "shòuhuòyuán", meaning: "salesperson", level: "HSK4" },
  { hanzi: "输", pinyin: "shū", meaning: "lose", level: "HSK4" }
];
