export const sentences = [
  // HSK1
  { hanzi: "我是学生。", pinyin: "Wǒ shì xuéshēng.", thai: "ฉันเป็นนักเรียน", blank: "学生", level: "HSK1" },
  { hanzi: "你好吗？", pinyin: "Nǐ hǎo ma?", thai: "คุณสบายดีไหม", blank: "好", level: "HSK1" },
  { hanzi: "我很好。", pinyin: "Wǒ hěn hǎo.", thai: "ฉันสบายดี", blank: "好", level: "HSK1" },
  { hanzi: "他是老师。", pinyin: "Tā shì lǎoshī.", thai: "เขาเป็นครู", blank: "老师", level: "HSK1" },
  { hanzi: "这是什么？", pinyin: "Zhè shì shénme?", thai: "นี่คืออะไร", blank: "什么", level: "HSK1" },
  { hanzi: "我有一个苹果。", pinyin: "Wǒ yǒu yī gè píngguǒ.", thai: "ฉันมีแอปเปิ้ลหนึ่งลูก", blank: "苹果", level: "HSK1" },
  { hanzi: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzì?", thai: "คุณชื่ออะไร", blank: "什么", level: "HSK1" },
  { hanzi: "我爱你。", pinyin: "Wǒ ài nǐ.", thai: "ฉันรักคุณ", blank: "爱", level: "HSK1" },
  { hanzi: "他们是朋友。", pinyin: "Tāmen shì péngyǒu.", thai: "พวกเขาเป็นเพื่อน", blank: "朋友", level: "HSK1" },
  { hanzi: "我不喝茶。", pinyin: "Wǒ bù hē chá.", thai: "ฉันไม่ดื่มชา", blank: "茶", level: "HSK1" },
  { hanzi: "今天是星期一。", pinyin: "Jīntiān shì xīngqīyī.", thai: "วันนี้เป็นวันจันทร์", blank: "今天", level: "HSK1" },
  { hanzi: "你在哪儿？", pinyin: "Nǐ zài nǎr?", thai: "คุณอยู่ที่ไหน", blank: "哪儿", level: "HSK1" },
  { hanzi: "我想吃饺子。", pinyin: "Wǒ xiǎng chī jiǎozi.", thai: "ฉันอยากกินเกี๊ยว", blank: "饺子", level: "HSK1" },
  { hanzi: "她是我的朋友。", pinyin: "Tā shì wǒ de péngyǒu.", thai: "เธอเป็นเพื่อนของฉัน", blank: "朋友", level: "HSK1" },
  { hanzi: "我没有钱。", pinyin: "Wǒ méiyǒu qián.", thai: "ฉันไม่มีเงิน", blank: "钱", level: "HSK1" },
  { hanzi: "这本书很好看。", pinyin: "Zhè běn shū hěn hǎokàn.", thai: "หนังสือเล่มนี้น่าอ่านมาก", blank: "书", level: "HSK1" },
  { hanzi: "今天天气怎么样？", pinyin: "Jīntiān tiānqì zěnmeyàng?", thai: "วันนี้อากาศเป็นอย่างไร", blank: "天气", level: "HSK1" },
  { hanzi: "我家有四口人。", pinyin: "Wǒ jiā yǒu sì kǒu rén.", thai: "บ้านฉันมีสี่คน", blank: "家", level: "HSK1" },
  { hanzi: "他不是学生。", pinyin: "Tā bú shì xuéshēng.", thai: "เขาไม่ใช่นักเรียน", blank: "学生", level: "HSK1" },
  { hanzi: "我喝水。", pinyin: "Wǒ hē shuǐ.", thai: "ฉันดื่มน้ำ", blank: "水", level: "HSK1" },
  { hanzi: "你喜欢什么？", pinyin: "Nǐ xǐhuān shénme?", thai: "คุณชอบอะไร", blank: "喜欢", level: "HSK1" },
  { hanzi: "我们去学校。", pinyin: "Wǒmen qù xuéxiào.", thai: "พวกเราไปโรงเรียน", blank: "学校", level: "HSK1" },
  { hanzi: "她很漂亮。", pinyin: "Tā hěn piàoliang.", thai: "เธอสวยมาก", blank: "漂亮", level: "HSK1" },
  { hanzi: "我看书。", pinyin: "Wǒ kàn shū.", thai: "ฉันอ่านหนังสือ", blank: "书", level: "HSK1" },
  { hanzi: "他吃饭了。", pinyin: "Tā chīfàn le.", thai: "เขากินข้าวแล้ว", blank: "饭", level: "HSK1" },
  { hanzi: "我有一只猫。", pinyin: "Wǒ yǒu yī zhī māo.", thai: "ฉันมีแมวหนึ่งตัว", blank: "猫", level: "HSK1" },
  { hanzi: "今天很热。", pinyin: "Jīntiān hěn rè.", thai: "วันนี้ร้อนมาก", blank: "热", level: "HSK1" },
  { hanzi: "你多大了？", pinyin: "Nǐ duō dà le?", thai: "คุณอายุเท่าไหร่แล้ว", blank: "大", level: "HSK1" },
  { hanzi: "我是中国人。", pinyin: "Wǒ shì Zhōngguó rén.", thai: "ฉันเป็นคนจีน", blank: "中国", level: "HSK1" },
  { hanzi: "他来了。", pinyin: "Tā lái le.", thai: "เขามาแล้ว", blank: "来", level: "HSK1" },

  // HSK2
  { hanzi: "我每天运动。", pinyin: "Wǒ měitiān yùndòng.", thai: "ฉันออกกำลังกายทุกวัน", blank: "运动", level: "HSK2" },
  { hanzi: "你能帮我吗？", pinyin: "Nǐ néng bāng wǒ ma?", thai: "คุณช่วยฉันได้ไหม", blank: "帮", level: "HSK2" },
  { hanzi: "我已经吃过了。", pinyin: "Wǒ yǐjīng chī guò le.", thai: "ฉันกินแล้ว", blank: "已经", level: "HSK2" },
  { hanzi: "他昨天来的。", pinyin: "Tā zuótiān lái de.", thai: "เขามาเมื่อวาน", blank: "昨天", level: "HSK2" },
  { hanzi: "我正在学习。", pinyin: "Wǒ zhèngzài xuéxí.", thai: "ฉันกำลังเรียนอยู่", blank: "学习", level: "HSK2" },
  { hanzi: "你应该多喝水。", pinyin: "Nǐ yīnggāi duō hē shuǐ.", thai: "คุณควรดื่มน้ำให้มาก", blank: "应该", level: "HSK2" },
  { hanzi: "我觉得很累。", pinyin: "Wǒ juéde hěn lèi.", thai: "ฉันรู้สึกเหนื่อยมาก", blank: "累", level: "HSK2" },
  { hanzi: "他比我高。", pinyin: "Tā bǐ wǒ gāo.", thai: "เขาสูงกว่าฉัน", blank: "高", level: "HSK2" },
  { hanzi: "我想去中国。", pinyin: "Wǒ xiǎng qù Zhōngguó.", thai: "ฉันอยากไปจีน", blank: "中国", level: "HSK2" },
  { hanzi: "你会说中文吗？", pinyin: "Nǐ huì shuō zhōngwén ma?", thai: "คุณพูดภาษาจีนได้ไหม", blank: "中文", level: "HSK2" },
  { hanzi: "她穿红色的衣服。", pinyin: "Tā chuān hóngsè de yīfu.", thai: "เธอสวมเสื้อสีแดง", blank: "衣服", level: "HSK2" },
  { hanzi: "我们一起去吧。", pinyin: "Wǒmen yīqǐ qù ba.", thai: "ไปด้วยกันเถอะ", blank: "一起", level: "HSK2" },
  { hanzi: "这个问题很难。", pinyin: "Zhège wèntí hěn nán.", thai: "คำถามนี้ยากมาก", blank: "问题", level: "HSK2" },
  { hanzi: "我要买一本书。", pinyin: "Wǒ yào mǎi yī běn shū.", thai: "ฉันจะซื้อหนังสือหนึ่งเล่ม", blank: "书", level: "HSK2" },
  { hanzi: "你住在哪里？", pinyin: "Nǐ zhù zài nǎlǐ?", thai: "คุณอาศัยอยู่ที่ไหน", blank: "哪里", level: "HSK2" },
  { hanzi: "我今天上班。", pinyin: "Wǒ jīntiān shàngbān.", thai: "ฉันทำงานวันนี้", blank: "上班", level: "HSK2" },
  { hanzi: "他们结婚了。", pinyin: "Tāmen jiéhūn le.", thai: "พวกเขาแต่งงานแล้ว", blank: "结婚", level: "HSK2" },
  { hanzi: "我喜欢听音乐。", pinyin: "Wǒ xǐhuān tīng yīnyuè.", thai: "ฉันชอบฟังเพลง", blank: "音乐", level: "HSK2" },
  { hanzi: "你什么时候回来？", pinyin: "Nǐ shénme shíhòu huílái?", thai: "คุณจะกลับมาเมื่อไหร่", blank: "时候", level: "HSK2" },
  { hanzi: "我学中文两年了。", pinyin: "Wǒ xué zhōngwén liǎng nián le.", thai: "ฉันเรียนภาษาจีนมาสองปีแล้ว", blank: "中文", level: "HSK2" },
  { hanzi: "天气越来越冷。", pinyin: "Tiānqì yuèláiyuè lěng.", thai: "อากาศหนาวขึ้นเรื่อย ๆ", blank: "冷", level: "HSK2" },
  { hanzi: "我忘了带钥匙。", pinyin: "Wǒ wàng le dài yàoshi.", thai: "ฉันลืมพากุญแจมา", blank: "忘", level: "HSK2" },
  { hanzi: "他正在打电话。", pinyin: "Tā zhèngzài dǎ diànhuà.", thai: "เขากำลังโทรศัพท์อยู่", blank: "电话", level: "HSK2" },
  { hanzi: "我们明天见面。", pinyin: "Wǒmen míngtiān jiànmiàn.", thai: "พวกเราจะพบกันพรุ่งนี้", blank: "明天", level: "HSK2" },
  { hanzi: "你的中文很好。", pinyin: "Nǐ de zhōngwén hěn hǎo.", thai: "ภาษาจีนของคุณดีมาก", blank: "中文", level: "HSK2" },
  { hanzi: "我弟弟喜欢踢足球。", pinyin: "Wǒ dìdi xǐhuān tī zúqiú.", thai: "น้องชายฉันชอบเตะฟุตบอล", blank: "足球", level: "HSK2" },
  { hanzi: "今天我很开心。", pinyin: "Jīntiān wǒ hěn kāixīn.", thai: "วันนี้ฉันมีความสุขมาก", blank: "开心", level: "HSK2" },
  { hanzi: "他们在公园里散步。", pinyin: "Tāmen zài gōngyuán lǐ sànbù.", thai: "พวกเขาเดินเล่นในสวนสาธารณะ", blank: "公园", level: "HSK2" },
  { hanzi: "我没有时间。", pinyin: "Wǒ méiyǒu shíjiān.", thai: "ฉันไม่มีเวลา", blank: "时间", level: "HSK2" },
  { hanzi: "你去过北京吗？", pinyin: "Nǐ qù guò Běijīng ma?", thai: "คุณเคยไปปักกิ่งไหม", blank: "北京", level: "HSK2" },

  // HSK3
  { hanzi: "请把门关上。", pinyin: "Qǐng bǎ mén guān shàng.", thai: "กรุณาปิดประตูด้วย", blank: "门", level: "HSK3" },
  { hanzi: "我对历史很感兴趣。", pinyin: "Wǒ duì lìshǐ hěn gǎn xìngqù.", thai: "ฉันสนใจประวัติศาสตร์มาก", blank: "历史", level: "HSK3" },
  { hanzi: "他的成绩越来越好。", pinyin: "Tā de chéngjì yuèláiyuè hǎo.", thai: "ผลการเรียนของเขาดีขึ้นเรื่อย ๆ", blank: "成绩", level: "HSK3" },
  { hanzi: "我们需要更多时间。", pinyin: "Wǒmen xūyào gèng duō shíjiān.", thai: "พวกเราต้องการเวลามากกว่านี้", blank: "时间", level: "HSK3" },
  { hanzi: "你有什么计划？", pinyin: "Nǐ yǒu shénme jìhuà?", thai: "คุณมีแผนอะไรบ้าง", blank: "计划", level: "HSK3" },
  { hanzi: "我觉得你说得对。", pinyin: "Wǒ juéde nǐ shuō de duì.", thai: "ฉันคิดว่าคุณพูดถูก", blank: "觉得", level: "HSK3" },
  { hanzi: "这个城市很美丽。", pinyin: "Zhège chéngshì hěn měilì.", thai: "เมืองนี้สวยงามมาก", blank: "城市", level: "HSK3" },
  { hanzi: "你应该注意身体。", pinyin: "Nǐ yīnggāi zhùyì shēntǐ.", thai: "คุณควรดูแลสุขภาพด้วย", blank: "身体", level: "HSK3" },
  { hanzi: "她每天坚持跑步。", pinyin: "Tā měitiān jiānchí pǎobù.", thai: "เธอวิ่งทุกวันอย่างสม่ำเสมอ", blank: "跑步", level: "HSK3" },
  { hanzi: "我们去年去了北京。", pinyin: "Wǒmen qùnián qù le Běijīng.", thai: "พวกเราไปปักกิ่งเมื่อปีที่แล้ว", blank: "北京", level: "HSK3" },
  { hanzi: "他看起来很开心。", pinyin: "Tā kànqǐlái hěn kāixīn.", thai: "เขาดูมีความสุขมาก", blank: "开心", level: "HSK3" },
  { hanzi: "这件事很复杂。", pinyin: "Zhè jiàn shì hěn fùzá.", thai: "เรื่องนี้ซับซ้อนมาก", blank: "复杂", level: "HSK3" },
  { hanzi: "我希望你能来。", pinyin: "Wǒ xīwàng nǐ néng lái.", thai: "ฉันหวังว่าคุณจะมา", blank: "希望", level: "HSK3" },
  { hanzi: "你最喜欢哪种运动？", pinyin: "Nǐ zuì xǐhuān nǎ zhǒng yùndòng?", thai: "คุณชอบกีฬาประเภทไหนมากที่สุด", blank: "运动", level: "HSK3" },
  { hanzi: "我们应该保护环境。", pinyin: "Wǒmen yīnggāi bǎohù huánjìng.", thai: "พวกเราควรรักษาสิ่งแวดล้อม", blank: "环境", level: "HSK3" },
  { hanzi: "他的汉语说得很流利。", pinyin: "Tā de hànyǔ shuō de hěn liúlì.", thai: "เขาพูดภาษาจีนได้คล่องมาก", blank: "流利", level: "HSK3" },
  { hanzi: "我明天有一个重要的会议。", pinyin: "Wǒ míngtiān yǒu yī gè zhòngyào de huìyì.", thai: "พรุ่งนี้ฉันมีการประชุมสำคัญ", blank: "会议", level: "HSK3" },
  { hanzi: "这道菜的味道很好。", pinyin: "Zhè dào cài de wèidào hěn hǎo.", thai: "อาหารจานนี้อร่อยมาก", blank: "味道", level: "HSK3" },
  { hanzi: "他已经工作很多年了。", pinyin: "Tā yǐjīng gōngzuò hěn duō nián le.", thai: "เขาทำงานมาหลายปีแล้ว", blank: "工作", level: "HSK3" },
  { hanzi: "我不太明白这道题。", pinyin: "Wǒ bú tài míngbái zhè dào tí.", thai: "ฉันไม่ค่อยเข้าใจโจทย์ข้อนี้", blank: "明白", level: "HSK3" },
  { hanzi: "你的想法很有创意。", pinyin: "Nǐ de xiǎngfǎ hěn yǒu chuàngyì.", thai: "ความคิดของคุณสร้างสรรค์มาก", blank: "想法", level: "HSK3" },
  { hanzi: "我们需要互相帮助。", pinyin: "Wǒmen xūyào hùxiāng bāngzhù.", thai: "พวกเราต้องช่วยเหลือซึ่งกันและกัน", blank: "帮助", level: "HSK3" },
  { hanzi: "他打算明年去留学。", pinyin: "Tā dǎsuàn míngnián qù liúxué.", thai: "เขาวางแผนจะไปเรียนต่อต่างประเทศปีหน้า", blank: "留学", level: "HSK3" },
  { hanzi: "这家餐厅的服务很好。", pinyin: "Zhè jiā cāntīng de fúwù hěn hǎo.", thai: "ร้านอาหารนี้บริการดีมาก", blank: "服务", level: "HSK3" },
  { hanzi: "我花了很多时间学习。", pinyin: "Wǒ huā le hěn duō shíjiān xuéxí.", thai: "ฉันใช้เวลามากในการเรียน", blank: "时间", level: "HSK3" },
  { hanzi: "你参加过这种比赛吗？", pinyin: "Nǐ cānjiā guò zhè zhǒng bǐsài ma?", thai: "คุณเคยเข้าร่วมการแข่งขันแบบนี้ไหม", blank: "比赛", level: "HSK3" },
  { hanzi: "他终于找到了工作。", pinyin: "Tā zhōngyú zhǎodào le gōngzuò.", thai: "เขาหางานได้ในที่สุด", blank: "工作", level: "HSK3" },
  { hanzi: "我认识她很多年了。", pinyin: "Wǒ rènshi tā hěn duō nián le.", thai: "ฉันรู้จักเธอมาหลายปีแล้ว", blank: "认识", level: "HSK3" },
  { hanzi: "这种方法更有效率。", pinyin: "Zhè zhǒng fāngfǎ gèng yǒu xiàolǜ.", thai: "วิธีนี้มีประสิทธิภาพมากกว่า", blank: "方法", level: "HSK3" },
  { hanzi: "他刚刚离开了。", pinyin: "Tā gānggāng líkāi le.", thai: "เขาเพิ่งจะออกไป", blank: "离开", level: "HSK3" },

  // HSK4
  { hanzi: "他的演讲非常精彩。", pinyin: "Tā de yǎnjiǎng fēicháng jīngcǎi.", thai: "การบรรยายของเขายอดเยี่ยมมาก", blank: "演讲", level: "HSK4" },
  { hanzi: "我们需要解决这个问题。", pinyin: "Wǒmen xūyào jiějué zhège wèntí.", thai: "พวกเราต้องแก้ปัญหานี้", blank: "解决", level: "HSK4" },
  { hanzi: "他克服了很多困难。", pinyin: "Tā kèfú le hěn duō kùnnán.", thai: "เขาเอาชนะความยากลำบากได้มากมาย", blank: "困难", level: "HSK4" },
  { hanzi: "我认为这个计划可行。", pinyin: "Wǒ rènwéi zhège jìhuà kěxíng.", thai: "ฉันคิดว่าแผนนี้เป็นไปได้", blank: "计划", level: "HSK4" },
  { hanzi: "她的作品受到了很多赞扬。", pinyin: "Tā de zuòpǐn shòudào le hěn duō zànyáng.", thai: "ผลงานของเธอได้รับคำชมมากมาย", blank: "作品", level: "HSK4" },
  { hanzi: "他们合作完成了这个项目。", pinyin: "Tāmen hézuò wánchéng le zhège xiàngmù.", thai: "พวกเขาร่วมมือกันทำโครงการนี้สำเร็จ", blank: "合作", level: "HSK4" },
  { hanzi: "这种方法比较有效。", pinyin: "Zhè zhǒng fāngfǎ bǐjiào yǒuxiào.", thai: "วิธีนี้ค่อนข้างมีประสิทธิภาพ", blank: "方法", level: "HSK4" },
  { hanzi: "我对这个领域很陌生。", pinyin: "Wǒ duì zhège lǐngyù hěn mòshēng.", thai: "ฉันไม่คุ้นเคยกับสาขานี้มากนัก", blank: "领域", level: "HSK4" },
  { hanzi: "这件事需要我们共同努力。", pinyin: "Zhè jiàn shì xūyào wǒmen gòngtóng nǔlì.", thai: "เรื่องนี้ต้องการความพยายามร่วมกันของพวกเรา", blank: "努力", level: "HSK4" },
  { hanzi: "科技的进步改变了我们的生活。", pinyin: "Kējì de jìnbù gǎibiàn le wǒmen de shēnghuó.", thai: "ความก้าวหน้าทางเทคโนโลยีเปลี่ยนแปลงชีวิตของเรา", blank: "进步", level: "HSK4" },
  { hanzi: "她在工作中表现得非常出色。", pinyin: "Tā zài gōngzuò zhōng biǎoxiàn de fēicháng chūsè.", thai: "เธอทำงานได้ยอดเยี่ยมมาก", blank: "表现", level: "HSK4" },
  { hanzi: "我们应该重视教育的重要性。", pinyin: "Wǒmen yīnggāi zhòngshì jiàoyù de zhòngyàoxìng.", thai: "พวกเราควรให้ความสำคัญกับการศึกษา", blank: "教育", level: "HSK4" },
  { hanzi: "他表达了对环境问题的关注。", pinyin: "Tā biǎodá le duì huánjìng wèntí de guānzhù.", thai: "เขาแสดงความห่วงใยต่อปัญหาสิ่งแวดล้อม", blank: "环境", level: "HSK4" },
  { hanzi: "这项政策引起了广泛讨论。", pinyin: "Zhè xiàng zhèngcè yǐnqǐ le guǎngfàn tǎolùn.", thai: "นโยบายนี้ก่อให้เกิดการถกเถียงอย่างกว้างขวาง", blank: "政策", level: "HSK4" },
  { hanzi: "经济的发展带来了新的机会。", pinyin: "Jīngjì de fāzhǎn dài lái le xīn de jīhuì.", thai: "การพัฒนาเศรษฐกิจนำมาซึ่งโอกาสใหม่ ๆ", blank: "发展", level: "HSK4" },
  { hanzi: "我们必须遵守这些规定。", pinyin: "Wǒmen bìxū zūnshǒu zhèxiē guīdìng.", thai: "พวกเราต้องปฏิบัติตามกฎเหล่านี้", blank: "规定", level: "HSK4" },
  { hanzi: "他的行为让大家感到失望。", pinyin: "Tā de xíngwéi ràng dàjiā gǎndào shīwàng.", thai: "พฤติกรรมของเขาทำให้ทุกคนผิดหวัง", blank: "行为", level: "HSK4" },
  { hanzi: "这本书对我影响很大。", pinyin: "Zhè běn shū duì wǒ yǐngxiǎng hěn dà.", thai: "หนังสือเล่มนี้มีอิทธิพลต่อฉันมาก", blank: "影响", level: "HSK4" },
  { hanzi: "他申请了一所著名的大学。", pinyin: "Tā shēnqǐng le yī suǒ zhùmíng de dàxué.", thai: "เขาสมัครเข้ามหาวิทยาลัยที่มีชื่อเสียงแห่งหนึ่ง", blank: "大学", level: "HSK4" },
  { hanzi: "我们应该尊重彼此的意见。", pinyin: "Wǒmen yīnggāi zūnzhòng bǐcǐ de yìjiàn.", thai: "พวกเราควรเคารพความคิดเห็นของกันและกัน", blank: "意见", level: "HSK4" },
  { hanzi: "这次经历让我学到了很多。", pinyin: "Zhè cì jīnglì ràng wǒ xuédào le hěn duō.", thai: "ประสบการณ์ครั้งนี้ทำให้ฉันเรียนรู้มากมาย", blank: "经历", level: "HSK4" },
  { hanzi: "她努力工作实现了自己的梦想。", pinyin: "Tā nǔlì gōngzuò shíxiàn le zìjǐ de mèngxiǎng.", thai: "เธอทำงานหนักจนบรรลุความฝันของตัวเอง", blank: "梦想", level: "HSK4" },
  { hanzi: "政府采取了新的措施来改善情况。", pinyin: "Zhèngfǔ cǎiqǔ le xīn de cuòshī lái gǎishàn qíngkuàng.", thai: "รัฐบาลใช้มาตรการใหม่เพื่อปรับปรุงสถานการณ์", blank: "措施", level: "HSK4" },
  { hanzi: "我需要更多的信息才能做决定。", pinyin: "Wǒ xūyào gèng duō de xìnxī cái néng zuò juédìng.", thai: "ฉันต้องการข้อมูลมากกว่านี้จึงจะตัดสินใจได้", blank: "信息", level: "HSK4" },
  { hanzi: "他们花了三年时间完成这个研究。", pinyin: "Tāmen huā le sān nián shíjiān wánchéng zhège yánjiū.", thai: "พวกเขาใช้เวลาสามปีในการทำวิจัยนี้สำเร็จ", blank: "研究", level: "HSK4" },
  { hanzi: "这个地区的文化非常丰富。", pinyin: "Zhège dìqū de wénhuà fēicháng fēngfù.", thai: "วัฒนธรรมของภูมิภาคนี้หลากหลายมาก", blank: "文化", level: "HSK4" },
  { hanzi: "我们公司正在扩大规模。", pinyin: "Wǒmen gōngsī zhèngzài kuòdà guīmó.", thai: "บริษัทของเรากำลังขยายขนาด", blank: "公司", level: "HSK4" },
  { hanzi: "她总是给大家带来快乐。", pinyin: "Tā zǒng shì gěi dàjiā dài lái kuàilè.", thai: "เธอมักนำความสุขมาให้ทุกคนเสมอ", blank: "快乐", level: "HSK4" },
  { hanzi: "他的建议对我们很有帮助。", pinyin: "Tā de jiànyì duì wǒmen hěn yǒu bāngzhù.", thai: "คำแนะนำของเขามีประโยชน์กับพวกเรามาก", blank: "建议", level: "HSK4" },
  { hanzi: "我们需要找到更好的解决方案。", pinyin: "Wǒmen xūyào zhǎodào gèng hǎo de jiějué fāng'àn.", thai: "พวกเราต้องหาวิธีแก้ปัญหาที่ดีกว่านี้", blank: "解决", level: "HSK4" },
];
